"use client";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, CircleDot, FileText, FolderOpen, MessageCircleQuestion, RefreshCw, Search, ShieldCheck, X } from "lucide-react";
import { useApi } from "@/lib/auth/context";
import { useWorkspace } from "@/features/notes/workspace-context";
import { useHealthReviews } from "@/lib/storage/health-reviews";
import { useKnowledgeReviews } from "@/lib/storage/knowledge-reviews";
import { useOverlapReviews } from "@/lib/storage/overlap-reviews";
import { useLinkReviews } from "@/lib/storage/link-reviews";
import { useGapReviews } from "@/lib/storage/gap-reviews";
import { Button } from "@/components/ui/button";
import { Empty, ErrorMessage, Loading } from "@/components/common/primitives";
import type { HealthCategory, HealthFilters, HealthPriority, HealthReviewState, LibraryHealthItem } from "@/lib/intelligence/health";
import { openAskSlate } from "@/components/ask/ask-slate";

const categoryLabels: Record<HealthCategory, string> = { links: "Links", consistency: "Consistency", overlap: "Overlap", relationships: "Relationships", structure: "Structure", coverage: "Coverage", assets: "Assets", metadata: "Metadata", concepts: "Concepts", intelligence: "Intelligence" };
const priorityLabels: Record<HealthPriority, string> = { "needs-attention": "Needs attention", "worth-reviewing": "Worth reviewing", informational: "Informational" };

function useReviewInputs() {
  const workspace = useWorkspace(); const health = useHealthReviews(workspace.scope), knowledge = useKnowledgeReviews(workspace.scope), overlap = useOverlapReviews(workspace.scope), links = useLinkReviews(workspace.scope), gaps = useGapReviews(workspace.scope);
  return { health, reviews: { health: health.reviews, knowledge: knowledge.reviews, overlap: overlap.reviews, links: links.reviews, gaps: gaps.reviews } };
}
function HealthItemButton({ item, selected, onClick }: { item: LibraryHealthItem; selected: boolean; onClick: () => void }) {
  return <button className={`health-item ${selected ? "selected" : ""}`} onClick={onClick} aria-current={selected ? "true" : undefined}><span className={`health-priority health-priority-${item.priority}`}><span className="sr-only">{priorityLabels[item.priority]}: </span></span><span><strong>{item.title}</strong><small>{item.noteTitles.join(" ↔ ") || item.projectPath || categoryLabels[item.category]}</small><p>{item.summary}</p></span><span className="health-evidence">{item.evidenceLevel.replace("-", " ")}</span><ArrowUpRight size={15} /></button>;
}

export function LibraryHealthWorkspace() {
  const api = useApi(), workspace = useWorkspace(), reviewInput = useReviewInputs(); const [filters, setFilters] = useState<HealthFilters>({ status: "open", ...workspace.healthFilters }), [page, setPage] = useState(0), [selected, setSelected] = useState<string | null>(null), [refresh, setRefresh] = useState(0);
  const requestFilters = { ...filters, page, limit: 25 }; const query = useQuery({ queryKey: ["library-health", requestFilters, reviewInput.reviews, refresh], queryFn: ({ signal }) => api.libraryHealth({ filters: requestFilters, reviews: reviewInput.reviews, refresh: refresh > 0 }, signal), staleTime: 25_000 });
  const current = query.data?.items.find((entry) => entry.id === selected) ?? null;
  const update = <K extends keyof HealthFilters>(key: K, value: HealthFilters[K]) => { setFilters((state) => ({ ...state, [key]: value || undefined })); setPage(0); setSelected(null); };
  const review = (item: LibraryHealthItem) => {
    if (item.targetWorkspace === "link-health") workspace.navigate("link-health");
    else if (item.targetWorkspace === "knowledge-issues") workspace.openKnowledgeIssues({ kind: "note", noteId: item.targetPayload.noteId });
    else if (item.targetWorkspace === "knowledge-overlap") workspace.openKnowledgeOverlap({ kind: "note", noteId: item.targetPayload.noteId });
    else if (item.targetWorkspace === "link-opportunities") workspace.openLinkOpportunities({ kind: "note", noteId: item.targetPayload.noteId });
    else if (item.targetWorkspace === "knowledge-gaps") workspace.openKnowledgeGaps({ status: "open", project: item.targetPayload.project, concept: item.targetPayload.concept, selected: item.targetPayload.fingerprint });
    else if (item.targetWorkspace === "concepts") workspace.openConcept(item.targetPayload.concept);
    else if (item.targetWorkspace === "project-brain" && item.projectPath) workspace.openProjectBrain(item.projectPath);
    else if (item.targetWorkspace === "note" && item.noteIds[0]) workspace.open(item.noteIds[0]);
    else if (item.targetWorkspace === "assets" && item.noteIds[0]) workspace.open(item.noteIds[0]);
    else if (item.targetWorkspace === "diagnostics") workspace.setSettingsOpen(true);
  };
  const selectOffset = (offset: number) => { if (!query.data?.items.length) return; const index = Math.max(0, query.data.items.findIndex((entry) => entry.id === current?.id)); setSelected(query.data.items[(index + offset + query.data.items.length) % query.data.items.length].id); };
  if (query.isPending) return <Loading label="Collecting current maintenance findings…" />;
  if (query.error || !query.data) return <ErrorMessage error={query.error ?? new Error("Library Health is unavailable")} retry={() => query.refetch()} />;
  const data = query.data;
  return <div className="health-workspace"><header className="health-header"><div><span className="eyebrow">Quiet maintenance inbox</span><h1>Library Health</h1><p>{data.summary.open} item{data.summary.open === 1 ? "" : "s"} worth reviewing</p></div><div className="health-header-actions"><Button onClick={() => setSelected(data.items.find((item) => item.reviewState === "open")?.id ?? null)} disabled={!data.items.length}><ShieldCheck size={16} />Review next</Button>{filters.project && <Button variant="outline" onClick={() => workspace.openProjectBrain(filters.project!)}><FolderOpen size={15} />Open Project Brain</Button>}<Button variant="outline" onClick={() => setRefresh((value) => value + 1)}><RefreshCw size={15} />Refresh Health</Button></div></header>
    <div className="health-summary" aria-label="Library Health summary">{(["needs-attention", "worth-reviewing", "informational"] as const).map((priority) => <button key={priority} onClick={() => update("priority", filters.priority === priority ? undefined : priority)}><span>{priorityLabels[priority]}</span><strong>{data.summary.priorities[priority]}</strong></button>)}</div>
    <div className="health-category-summary" aria-label="Open findings by category">{(Object.keys(categoryLabels) as HealthCategory[]).filter((category) => data.summary.categories[category] > 0).map((category) => <button key={category} onClick={() => update("category", filters.category === category ? undefined : category)}><span>{categoryLabels[category]}</span><strong>{data.summary.categories[category]}</strong></button>)}</div>
    <div className="health-filters"><label><Search size={15} /><span className="sr-only">Search maintenance findings</span><input value={filters.search ?? ""} onChange={(event) => update("search", event.target.value)} placeholder="Find a note, path, project, or issue…" /></label><select aria-label="Health category" value={filters.category ?? ""} onChange={(event) => update("category", event.target.value as HealthCategory || undefined)}><option value="">All categories</option>{Object.entries(categoryLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Health project" value={filters.project ?? ""} onChange={(event) => update("project", event.target.value)}><option value="">All projects</option>{data.projects.map((path) => <option key={path} value={path}>{path}</option>)}</select><select aria-label="Health status" value={filters.status ?? ""} onChange={(event) => update("status", event.target.value as HealthReviewState || undefined)}><option value="">Any status</option><option value="open">Open</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option><option value="not-relevant">Not relevant</option></select><select aria-label="Health concept" value={filters.concept ?? ""} onChange={(event) => update("concept", event.target.value)}><option value="">All concepts</option>{data.concepts.map((concept) => <option key={concept.id} value={concept.id}>{concept.name}</option>)}</select></div>
    {data.degraded && <p className="health-degraded" role="status">{data.degraded}</p>}
    <div className={`health-body ${current ? "has-detail" : ""}`}><div className="health-list scroll-area">{(["needs-attention", "worth-reviewing", "informational"] as const).map((priority) => { const items = data.items.filter((entry) => entry.priority === priority); return items.length ? <section key={priority} aria-labelledby={`health-${priority}`}><h2 id={`health-${priority}`}>{priorityLabels[priority]} <span>{items.length}</span></h2>{items.map((entry) => <HealthItemButton key={entry.id} item={entry} selected={entry.id === current?.id} onClick={() => setSelected(entry.id)} />)}</section> : null; })}{!data.items.length && <Empty title="Nothing matches these filters" detail="Try another project, category, status, or search term." />}{data.total > data.pageSize && <div className="pagination"><Button variant="ghost" size="sm" disabled={!page} onClick={() => setPage((value) => value - 1)}>Previous</Button><span>Page {page + 1}</span><Button variant="ghost" size="sm" disabled={(page + 1) * data.pageSize >= data.total} onClick={() => setPage((value) => value + 1)}>Next</Button></div>}</div>
      {current && <aside className="health-detail scroll-area" aria-label="Maintenance item details"><button className="health-detail-close" onClick={() => setSelected(null)} aria-label="Close maintenance details"><X size={18} /></button><span className="eyebrow">{categoryLabels[current.category]} · {priorityLabels[current.priority]}</span><h2>{current.title}</h2><p>{current.summary}</p><dl><div><dt>Evidence</dt><dd>{current.evidenceLevel.replace("-", " ")}</dd></div><div><dt>Status</dt><dd>{current.reviewState.replace("-", " ")}</dd></div><div><dt>Source</dt><dd>{current.sourceSystem}</dd></div></dl>{current.reasons.length > 0 && <section><h3>Why this was flagged</h3><ul>{current.reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></section>}{current.paths.length > 0 && <section><h3>Sources</h3>{current.paths.map((path, index) => <button key={path} onClick={() => current.noteIds[index] && workspace.open(current.noteIds[index])}>{current.noteTitles[index] ?? path}<small>{path}</small></button>)}</section>}<div className="health-detail-actions"><Button onClick={() => review(current)}>Review <ArrowUpRight size={15} /></Button>{current.noteIds[0] && <Button variant="outline" onClick={() => workspace.open(current.noteIds[0])}><FileText size={15} />Open note</Button>}{current.noteIds.length > 0 && <Button variant="ghost" onClick={() => openAskSlate({ scope: "selected", noteIds: current.noteIds.slice(0, 20), question: `Explain why this maintenance item was flagged and what evidence supports it: ${current.title}` })}><MessageCircleQuestion size={15} />Ask Slate</Button>}{current.healthOnly && <><Button variant="outline" onClick={() => reviewInput.health.setReview(current.fingerprint, "resolved")}><Check size={15} />Resolved</Button><Button variant="ghost" onClick={() => reviewInput.health.setReview(current.fingerprint, "dismissed")}>Dismiss</Button><Button variant="ghost" onClick={() => reviewInput.health.setReview(current.fingerprint, "not-relevant")}>Not relevant</Button></>}</div><footer><Button variant="ghost" size="sm" onClick={() => selectOffset(-1)}><ArrowLeft size={14} />Previous</Button><Button variant="ghost" size="sm" onClick={() => selectOffset(1)}>Next<ArrowRight size={14} /></Button></footer></aside>}
    </div><details className="knowledge-diagnostics"><summary>Health diagnostics</summary><dl>{Object.entries(data.diagnostics).map(([key, value]) => <div key={key}><dt>{key.replace(/([A-Z])/g, " $1")}</dt><dd>{Array.isArray(value) ? value.join(", ") || "None" : String(value)}</dd></div>)}</dl></details></div>;
}

export function ProjectHealthSummary({ path }: { path: string }) { const api = useApi(), workspace = useWorkspace(), { reviews } = useReviewInputs(); const query = useQuery({ queryKey: ["health-summary", "project", path, reviews], queryFn: ({ signal }) => api.libraryHealth({ filters: { project: path, status: "open", limit: 1 }, reviews }, signal), staleTime: 30_000 }); if (!query.data) return null; return <button className="health-inline-summary" onClick={() => workspace.openLibraryHealth({ project: path, status: "open" })}><CircleDot size={15} /><span><strong>Library Health / Maintenance</strong><small>{query.data.total} item{query.data.total === 1 ? "" : "s"} worth reviewing in this project</small></span><ArrowUpRight size={15} /></button>; }
export function CurrentNoteMaintenance({ noteId }: { noteId: string }) { const api = useApi(), workspace = useWorkspace(), { reviews } = useReviewInputs(); const query = useQuery({ queryKey: ["health-summary", "note", noteId, reviews], queryFn: ({ signal }) => api.libraryHealth({ filters: { noteId, status: "open", limit: 5 }, reviews }, signal), staleTime: 30_000 }); if (!query.data?.total) return null; return <section className="rail-concepts"><h3>Maintenance <span>{query.data.total}</span></h3>{query.data.items.slice(0, 3).map((item) => <button key={item.id} onClick={() => workspace.openLibraryHealth({ noteId, status: "open", category: item.category })}><strong>{item.title}</strong><small>{priorityLabels[item.priority]}</small></button>)}</section>; }
export function ConceptHealthSummary({ conceptId, conceptName }: { conceptId: string; conceptName: string }) { const api = useApi(), workspace = useWorkspace(), { reviews } = useReviewInputs(); const query = useQuery({ queryKey: ["health-summary", "concept", conceptId, reviews], queryFn: ({ signal }) => api.libraryHealth({ filters: { concept: conceptId, status: "open", limit: 1 }, reviews }, signal), staleTime: 30_000 }); if (!query.data?.total) return null; return <button className="health-inline-summary" onClick={() => workspace.openLibraryHealth({ concept: conceptId, status: "open" })}><CircleDot size={15} /><span><strong>Knowledge maintenance</strong><small>{query.data.total} finding{query.data.total === 1 ? "" : "s"} involving {conceptName}</small></span><ArrowUpRight size={15} /></button>; }
