"use client";
import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, Check, CircleHelp, Copy, FileText, MessageCircleQuestion, RefreshCw, Search, X } from "lucide-react";
import { useApi } from "@/lib/auth/context";
import { useWorkspace } from "@/features/notes/workspace-context";
import { useGapReviews } from "@/lib/storage/gap-reviews";
import { Button } from "@/components/ui/button";
import { Empty, ErrorMessage, Loading } from "@/components/common/primitives";
import { createGapDraft, gapKindLabel, type GapFilters, type GapImportance, type GapReviewState, type KnowledgeGap, type KnowledgeGapKind } from "@/lib/intelligence/knowledge-gaps";
import { openAskSlate } from "@/components/ask/ask-slate";

const kindOrder: KnowledgeGapKind[] = ["thin-coverage", "fragmented-coverage", "missing-overview", "missing-architecture-explanation", "missing-decision-rationale", "missing-operational-explanation", "missing-failure-recovery-knowledge", "recurring-unanswered-question", "missing-bridge-knowledge", "integration-gap"];
const importanceLabels: Record<GapImportance, string> = { high: "High relevance", medium: "Relevant", low: "Lower relevance" };

function useGapReviewInput() { const workspace = useWorkspace(), local = useGapReviews(workspace.scope); return { local, reviews: { gaps: local.reviews } }; }
function GapRow({ gap, selected, onSelect }: { gap: KnowledgeGap; selected: boolean; onSelect: () => void }) { return <button className={`gap-row ${selected ? "selected" : ""}`} onClick={onSelect} aria-current={selected ? "true" : undefined}><span><strong>{gap.title}</strong><small>{gapKindLabel(gap.kind)} · {importanceLabels[gap.importanceLevel]}</small><p>{gap.summary}</p></span><span className="gap-source-count">{gap.noteIds.length} source{gap.noteIds.length === 1 ? "" : "s"}</span><ArrowUpRight size={15} /></button>; }

export function KnowledgeGapsWorkspace() {
  const api = useApi(), workspace = useWorkspace(), reviewInput = useGapReviewInput(); const [filters, setFilters] = useState<GapFilters>({ status: "open", ...workspace.gapFilters }), [page, setPage] = useState(0), [selected, setSelected] = useState<string | null>(workspace.gapFilters.selected ?? null), [rebuild, setRebuild] = useState(0), [draft, setDraft] = useState<{ gap: KnowledgeGap; text: string } | null>(null); const lastTrigger = useRef<HTMLElement | null>(null);
  const requestFilters = { ...filters, selected: undefined, page, limit: 20 }; const query = useQuery({ queryKey: ["knowledge-gaps", requestFilters, reviewInput.reviews, rebuild], queryFn: ({ signal }) => api.knowledgeGaps({ filters: requestFilters, reviews: reviewInput.reviews, ...(rebuild ? { action: "rebuild" as const, confirm: true } : {}) }, signal), staleTime: 55_000 });
  const current = query.data?.items.find((item) => item.fingerprint === selected || item.id === selected) ?? null;
  useEffect(() => { if (!draft && lastTrigger.current?.isConnected) lastTrigger.current.focus(); }, [draft]);
  const update = <K extends keyof GapFilters>(key: K, value: GapFilters[K]) => { setFilters((state) => ({ ...state, [key]: value || undefined })); setPage(0); setSelected(null); };
  const route = (gap: KnowledgeGap) => { if (gap.targetWorkspace === "concepts" && gap.conceptName) workspace.openConcept(gap.conceptName); else if (gap.targetWorkspace === "project-brain" && gap.projectPath) workspace.openProjectBrain(gap.projectPath); else if (gap.targetWorkspace === "knowledge-overlap" && gap.noteIds[0]) workspace.openKnowledgeOverlap({ kind: "note", noteId: gap.noteIds[0] }); else if (gap.targetWorkspace === "link-opportunities" && gap.noteIds[0]) workspace.openLinkOpportunities({ kind: "note", noteId: gap.noteIds[0] }); else if (gap.targetWorkspace === "knowledge-issues" && gap.noteIds[0]) workspace.openKnowledgeIssues({ kind: "note", noteId: gap.noteIds[0] }); else if (gap.noteIds[0]) workspace.open(gap.noteIds[0]); };
  const ask = (gap: KnowledgeGap, question = "What do I already know about this, where is the coverage weak, and which sources should I review first?") => openAskSlate(gap.noteIds.length ? { scope: "selected", noteIds: gap.noteIds.slice(0, 20), question } : gap.projectPath ? { scope: "project", path: gap.projectPath, question } : { scope: "library", question });
  const openDraft = (gap: KnowledgeGap, trigger: HTMLElement) => { lastTrigger.current = trigger; const key = `slate.gap-draft.v1.${workspace.scope}.${gap.fingerprint}`, text = sessionStorage.getItem(key) ?? createGapDraft(gap); sessionStorage.setItem(key, text); setDraft({ gap, text }); };
  const selectOffset = (offset: number) => { if (!query.data?.items.length) return; const index = Math.max(0, query.data.items.findIndex((item) => item.id === current?.id)); setSelected(query.data.items[(index + offset + query.data.items.length) % query.data.items.length].id); };
  if (query.isPending) return <Loading label="Reviewing current library coverage…" />;
  if (query.error || !query.data) return <ErrorMessage error={query.error ?? new Error("Knowledge Gaps is unavailable")} retry={() => query.refetch()} />;
  const data = query.data;
  return <div className="gap-workspace"><header className="gap-header"><div><span className="eyebrow">Library coverage observations</span><h1>Knowledge Gaps</h1><p>{data.summary.open} possible gap{data.summary.open === 1 ? "" : "s"}</p></div><div className="gap-header-actions"><Button onClick={() => setSelected(data.items.find((item) => item.reviewState === "open")?.id ?? null)} disabled={!data.items.length}><BookOpen size={16} />Review next</Button><Button variant="outline" onClick={() => { if (confirm("Rebuild derived Knowledge Gap findings? This does not change any notes.")) setRebuild((value) => value + 1); }}><RefreshCw size={15} />Rebuild Knowledge Gaps</Button></div></header>
    <div className="gap-summary" aria-label="Knowledge Gap summary">{(["high", "medium", "low"] as const).map((importance) => <button key={importance} onClick={() => update("importance", filters.importance === importance ? undefined : importance)}><span>{importanceLabels[importance]}</span><strong>{data.summary.importance[importance]}</strong></button>)}</div>
    <div className="gap-kind-summary" aria-label="Knowledge gaps by type">{kindOrder.filter((kind) => data.summary.kinds[kind]).slice(0, 6).map((kind) => <button key={kind} onClick={() => update("kind", filters.kind === kind ? undefined : kind)}><span>{gapKindLabel(kind)}</span><strong>{data.summary.kinds[kind]}</strong></button>)}</div>
    <div className="gap-filters"><label><Search size={15} /><span className="sr-only">Search coverage observations</span><input value={filters.search ?? ""} onChange={(event) => update("search", event.target.value)} placeholder="Find a concept, project, source, or observation…" /></label><select aria-label="Gap type" value={filters.kind ?? ""} onChange={(event) => update("kind", event.target.value as KnowledgeGapKind || undefined)}><option value="">All types</option>{kindOrder.map((kind) => <option key={kind} value={kind}>{gapKindLabel(kind)}</option>)}</select><select aria-label="Gap project" value={filters.project ?? ""} onChange={(event) => update("project", event.target.value)}><option value="">All projects</option>{data.projects.map((path) => <option key={path} value={path}>{path}</option>)}</select><select aria-label="Gap concept" value={filters.concept ?? ""} onChange={(event) => update("concept", event.target.value)}><option value="">All concepts</option>{data.concepts.map((concept) => <option key={concept.id} value={concept.id}>{concept.name}</option>)}</select><select aria-label="Gap review state" value={filters.status ?? ""} onChange={(event) => update("status", event.target.value as GapReviewState || undefined)}><option value="">Any state</option><option value="open">Open</option><option value="addressed">Addressed</option><option value="dismissed">Dismissed</option><option value="not-relevant">Not relevant</option><option value="intentionally-fragmented">Intentionally fragmented</option></select></div>
    {data.degraded && <p className="gap-degraded" role="status">{data.degraded}</p>}
    <div className={`gap-body ${current ? "has-detail" : ""}`}><div className="gap-list scroll-area">{data.items.map((gap) => <GapRow key={gap.id} gap={gap} selected={gap.id === current?.id} onSelect={() => setSelected(gap.id)} />)}{!data.items.length && <Empty title="No coverage observations match" detail="Try another project, concept, type, or review state." />}{data.total > data.pageSize && <div className="pagination"><Button variant="ghost" size="sm" disabled={!page} onClick={() => setPage((value) => value - 1)}>Previous</Button><span>Page {page + 1}</span><Button variant="ghost" size="sm" disabled={(page + 1) * data.pageSize >= data.total} onClick={() => setPage((value) => value + 1)}>Next</Button></div>}</div>
      {current && <aside className="gap-detail scroll-area" aria-label="Knowledge gap details"><button className="gap-detail-close" onClick={() => setSelected(null)} aria-label="Close knowledge gap details"><X size={18} /></button><span className="eyebrow">{gapKindLabel(current.kind)} · {importanceLabels[current.importanceLevel]}</span><h2>{current.title}</h2><p>{current.summary}</p><section><h3>Why flagged</h3><ul>{current.signals.map((signal) => <li key={signal}>{signal}</li>)}</ul></section>{current.sourceConceptIds.length > 1 && <section><h3>Related concepts</h3><p>{current.sourceConceptIds.length} concepts participate in this observation.</p></section>}<details open><summary>Existing coverage <span>{current.evidence.length}</span></summary><div className="gap-sources">{current.evidence.map((source) => <button key={`${source.noteId}:${source.path}`} onClick={() => workspace.open(source.noteId)}><span><strong>{source.title}</strong><small>{source.path}</small></span><span>{source.substantial ? "Substantial" : `${source.explanatoryWords} explanatory words`}</span></button>)}</div></details><div className="gap-detail-actions"><Button onClick={() => route(current)}>Review <ArrowUpRight size={15} /></Button><Button variant="outline" onClick={() => ask(current)}><MessageCircleQuestion size={15} />Ask Slate</Button><Button variant="outline" onClick={(event) => openDraft(current, event.currentTarget)}><FileText size={15} />Create Draft</Button>{current.noteIds[0] && <Button variant="ghost" onClick={() => workspace.open(current.noteIds[0])}>Open source</Button>}<Button variant="ghost" onClick={() => reviewInput.local.setReview(current.fingerprint, "addressed")}><Check size={15} />Addressed</Button><Button variant="ghost" onClick={() => reviewInput.local.setReview(current.fingerprint, "dismissed")}>Dismiss</Button><Button variant="ghost" onClick={() => reviewInput.local.setReview(current.fingerprint, "not-relevant")}>Not relevant</Button>{current.kind === "fragmented-coverage" && <Button variant="ghost" onClick={() => reviewInput.local.setReview(current.fingerprint, "intentionally-fragmented")}>Keep fragmented</Button>}</div><footer><Button variant="ghost" size="sm" onClick={() => selectOffset(-1)}><ArrowLeft size={14} />Previous</Button><Button variant="ghost" size="sm" onClick={() => selectOffset(1)}>Next<ArrowRight size={14} /></Button></footer></aside>}
    </div><details className="knowledge-diagnostics"><summary>Gap diagnostics</summary><dl>{Object.entries(data.diagnostics).map(([key, value]) => <div key={key}><dt>{key.replace(/([A-Z])/g, " $1")}</dt><dd>{String(value)}</dd></div>)}</dl></details>
    {draft && <div className="gap-draft-backdrop" role="presentation"><section className="gap-draft" role="dialog" aria-modal="true" aria-labelledby="gap-draft-title"><header><div><span className="eyebrow">Browser-local draft</span><h2 id="gap-draft-title">{draft.gap.title}</h2></div><button onClick={() => setDraft(null)} aria-label="Close draft preview"><X size={18} /></button></header><p>This source-linked template stays in this browser session. It has not been saved to your library.</p><textarea aria-label="Knowledge gap draft" value={draft.text} onChange={(event) => { const text = event.target.value; sessionStorage.setItem(`slate.gap-draft.v1.${workspace.scope}.${draft.gap.fingerprint}`, text); setDraft({ ...draft, text }); }} /><footer><Button variant="outline" onClick={() => navigator.clipboard.writeText(draft.text)}><Copy size={15} />Copy draft</Button><Button onClick={() => setDraft(null)}>Done</Button></footer></section></div>}
  </div>;
}

export function ProjectGapSummary({ path }: { path: string }) { const api = useApi(), workspace = useWorkspace(), { reviews } = useGapReviewInput(); const query = useQuery({ queryKey: ["gap-summary", "project", path, reviews], queryFn: ({ signal }) => api.knowledgeGaps({ filters: { project: path, status: "open", limit: 3 }, reviews }, signal), staleTime: 60_000 }); if (!query.data?.total) return null; return <button className="gap-inline-summary" onClick={() => workspace.openKnowledgeGaps({ project: path, status: "open" })}><CircleHelp size={15} /><span><strong>Knowledge Gaps</strong><small>{query.data.total} coverage observation{query.data.total === 1 ? "" : "s"} in this project</small></span><ArrowUpRight size={15} /></button>; }
export function ConceptCoverageSummary({ conceptId, conceptName }: { conceptId: string; conceptName: string }) { const api = useApi(), workspace = useWorkspace(), { reviews } = useGapReviewInput(); const query = useQuery({ queryKey: ["gap-summary", "concept", conceptId, reviews], queryFn: ({ signal }) => api.knowledgeGaps({ filters: { concept: conceptId, status: "open", limit: 3 }, reviews }, signal), staleTime: 60_000 }); if (!query.data) return null; return <section className="concept-coverage"><header><div><span className="eyebrow">Coverage</span><h2>Coverage observations</h2></div><Button variant="ghost" size="sm" onClick={() => workspace.openKnowledgeGaps({ concept: conceptId, status: "open" })}>Open Gap Finder<ArrowUpRight size={14} /></Button></header>{query.data.items.length ? <ul>{query.data.items.map((gap) => <li key={gap.id}><strong>{gapKindLabel(gap.kind)}</strong><span>{gap.summary}</span></li>)}</ul> : <p>No conservative coverage gap is currently identified for {conceptName}.</p>}</section>; }
