import { test, expect, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { connect, mockSlate, second } from "./fixture";

async function openInbox(page:Page, options:Parameters<typeof mockSlate>[1]={}) { const state=await mockSlate(page,options); await connect(page); await page.getByRole("button",{name:"Inbox",exact:true}).first().click(); await expect(page.getByRole("heading",{name:/^Inbox/})).toBeVisible(); return state; }
async function openAppend(page:Page) { await page.getByRole("button",{name:/Append to Reading list/}).click(); return page.getByRole("dialog",{name:"Append to existing note"}); }

test("1. opens the dedicated Inbox triage workspace",async({page})=>{await openInbox(page);await expect(page.getByText("Review one thought at a time. Slate suggests; you decide.")).toBeVisible();});
test("2. capture has an intelligence summary",async({page})=>{await openInbox(page);await expect(page.getByText(/Question · unprocessed/)).toBeVisible();await expect(page.getByText(/Question capture with related material|The capture is phrased/)).toBeVisible();});
test("3. likely project appears",async({page})=>{await openInbox(page);await expect(page.getByText("Projects/Slate",{exact:true})).toBeVisible();});
test("4. related concepts appear",async({page})=>{await openInbox(page);const concepts=page.locator(".inbox-concepts");await expect(concepts.getByText("Slate",{exact:true})).toBeVisible();await expect(concepts.getByText("PostgreSQL",{exact:true})).toBeVisible();});
test("5. related notes appear and open",async({page})=>{await openInbox(page);await expect(page.getByRole("button",{name:/Reading list Exact topic match/})).toBeVisible();});
test("6. duplicate and 7. partial-overlap evidence are explicit",async({page})=>{await openInbox(page);await expect(page.getByText("Partial overlap",{exact:true})).toBeVisible();await page.getByRole("button",{name:"Similar knowledge exists"}).click();await expect(page.getByRole("heading",{name:"Knowledge Overlap",exact:true})).toBeVisible();});
test("8. Convert to Question preview and 9. cancel",async({page})=>{await openInbox(page);await page.getByRole("button",{name:"Review",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Convert to Question"});await expect(dialog.getByText(/type: question/)).toBeVisible();await dialog.getByRole("button",{name:"Cancel"}).click();await expect(dialog).toHaveCount(0);});
test("10. Append preview and 11. browser draft only",async({page})=>{const state=await openInbox(page);const writes=state.requests.filter((request)=>request.method==="PUT").length;const dialog=await openAppend(page);await expect(dialog.getByLabel("Proposed browser draft")).toHaveValue(/## Captured thought/);await dialog.getByRole("button",{name:"Open as browser draft"}).click();expect(state.requests.filter((request)=>request.method==="PUT")).toHaveLength(writes);await expect(page.getByRole("dialog",{name:/Recover your draft/})).toBeVisible();});
test("12. target saves through the normal revision-protected flow",async({page})=>{const state=await openInbox(page);const dialog=await openAppend(page);await dialog.getByRole("button",{name:"Open as browser draft"}).click();await page.getByRole("button",{name:"Continue editing draft"}).click();await page.getByRole("button",{name:"Save note"}).click();await expect.poll(()=>state.requests.some((request)=>request.method==="PUT"&&request.path.includes("v1/notes/"))).toBe(true);});
test("12b. append blocks a stale target revision",async({page})=>{const state=await openInbox(page);const dialog=await openAppend(page);const target=state.notes.get(second)!;state.notes.set(second,{...target,revision:"server-changed",markdown:`${target.markdown}\n\nChanged elsewhere.`});await dialog.getByRole("button",{name:"Open as browser draft"}).click();await expect(dialog.getByText(/target note changed after this preview/)).toBeVisible();expect(state.requests.filter((request)=>request.method==="PUT")).toHaveLength(0);});
test("13. Create Note from Capture previews before writing",async({page})=>{await openInbox(page);await page.getByRole("button",{name:"Create New Note"}).click();const dialog=page.getByRole("dialog",{name:"Create note from capture"});await expect(dialog.getByLabel("Content")).not.toBeEmpty();await expect(dialog.getByRole("textbox",{name:"Destination folder"})).toHaveValue("Projects");});
test("14. Move suggestion uses the existing confirmation",async({page})=>{await openInbox(page);await page.getByRole("button",{name:"Move to Projects"}).click();await expect(page.getByRole("dialog",{name:"Move to folder"})).toBeVisible();await expect(page.getByLabel("Destination folder",{exact:true})).toHaveValue("Projects");});
test("15. multiple possible projects remain visible",async({page})=>{await openInbox(page);await expect(page.getByText("Projects/Slate",{exact:true})).toBeVisible();await expect(page.getByText("Projects/ReplayOps",{exact:true})).toBeVisible();});
test("16. dismisses only the suggestion",async({page})=>{await openInbox(page);await page.getByRole("button",{name:"Dismiss suggestion"}).click();await expect(page.getByText("Convert to Question",{exact:true})).toHaveCount(0);await expect(page.getByRole("heading",{name:"Library architecture",exact:true})).toBeVisible();});
test("17. Mark processed persists in browser state",async({page})=>{await openInbox(page);await page.getByRole("button",{name:"Keep",exact:true}).click();await expect(page.getByText("Inbox reviewed")).toBeVisible();await page.getByLabel("Filter Inbox review state").selectOption("processed");await expect(page.getByText("Question · processed",{exact:true})).toBeVisible();});
test("18. Later defers the capture",async({page})=>{await openInbox(page);await page.getByRole("button",{name:"Later",exact:true}).click();await expect(page.getByText("Inbox reviewed")).toBeVisible();await page.getByLabel("Filter Inbox review state").selectOption("deferred");await expect(page.getByText(/deferred/)).toBeVisible();});
test("19. Inbox Zero advances after a reviewed action",async({page})=>{await openInbox(page);await page.getByRole("button",{name:"Inbox Zero"}).click();await expect(page.getByText(/1 remaining/)).toBeVisible();await page.getByRole("button",{name:"Keep",exact:true}).click();await expect(page.getByText("Inbox reviewed")).toBeVisible();});
test("20. Knowledge Gap relationship opens Gap Finder",async({page})=>{await openInbox(page);await page.getByRole("button",{name:/PostgreSQL operations/}).click();await expect(page.getByRole("heading",{name:"Knowledge Gaps",exact:true})).toBeVisible();});
test("21. Ask Slate uses the capture and bounded related notes",async({page})=>{const state=await openInbox(page);await page.getByTestId("document").getByRole("button",{name:"Ask Slate",exact:true}).click();await expect(page.getByRole("heading",{name:"Ask Slate",exact:true})).toBeVisible();await page.getByRole("button",{name:"Ask Slate",exact:true}).last().click();await expect.poll(()=>state.askRequests.length).toBe(1);expect(state.askRequests[0].scope.noteIds?.length).toBeLessThanOrEqual(6);expect(state.askRequests[0].scope.selectedText?.length).toBeGreaterThan(0);});
test("22. generation-disabled deterministic triage remains functional",async({page})=>{await openInbox(page,{generationEnabled:false,semanticEnabled:false});await expect(page.getByText(/Deterministic Inbox triage is active/)).toBeVisible();await expect(page.getByText("Convert to Question",{exact:true})).toBeVisible();});
test("23. mobile Inbox Zero has large one-item actions",async({page})=>{await page.setViewportSize({width:390,height:844});await openInbox(page);await page.getByRole("button",{name:"Inbox Zero"}).click();await expect(page.getByRole("button",{name:"Keep",exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test("24. mobile append preview is full screen and editable",async({page})=>{await page.setViewportSize({width:390,height:844});await openInbox(page);await page.getByRole("button",{name:"Inbox Zero"}).click();const dialog=await openAppend(page);await expect(dialog.getByLabel("Proposed browser draft")).toBeEditable();expect(await dialog.evaluate((element)=>Math.abs(element.getBoundingClientRect().width-innerWidth)<3)).toBe(true);});
test("25. desktop Inbox passes axe",async({page})=>{await openInbox(page);expect((await new AxeBuilder({page}).include(".inbox-triage").analyze()).violations).toEqual([]);});
test("26. mobile Inbox passes axe",async({page})=>{await page.setViewportSize({width:390,height:844});await openInbox(page);await page.getByRole("button",{name:"Inbox Zero"}).click();expect((await new AxeBuilder({page}).include(".inbox-triage").analyze()).violations).toEqual([]);});
