import { test, expect, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { connect, mockSlate } from "./fixture";

async function openGaps(page: Page, options: Parameters<typeof mockSlate>[1] = {}) {
  await mockSlate(page, options); await connect(page);
  await page.keyboard.press("Control+Shift+P");
  await page.getByRole("combobox").fill("> knowledge gaps");
  await page.getByRole("option").filter({ hasText: "Knowledge Gaps" }).first().click();
  await expect(page.getByRole("heading", { name: "Knowledge Gaps", exact: true })).toBeVisible();
}
async function selectGap(page: Page, name: RegExp) {
  await page.locator(".gap-list").getByRole("button", { name }).first().click();
  await expect(page.getByRole("complementary", { name: "Knowledge gap details" })).toBeVisible();
}
async function openKubernetes(page: Page) {
  await page.keyboard.press("Control+Shift+P"); await page.getByRole("combobox").fill("> browse concepts");
  await page.getByRole("option").filter({ hasText: "Browse Concepts" }).click();
  await page.getByPlaceholder(/Find Kubernetes/).fill("Kubernetes");
  await page.getByRole("button", { name: /Kubernetes Technology/ }).click();
  await expect(page.getByRole("heading", { name: "Kubernetes", exact: true })).toBeVisible();
}
async function openProject(page: Page) {
  await page.getByRole("button", { name: "Actions for Projects" }).first().click();
  await page.getByRole("menuitem", { name: "Open Project Brain" }).click();
  await expect(page.getByRole("heading", { name: "Projects", exact: true })).toBeVisible();
}

test("1. opens Knowledge Gaps from Command Center", async ({ page }) => { await openGaps(page); });
test("2. views a Thin Coverage finding", async ({ page }) => { await openGaps(page); await expect(page.getByRole("button", { name: /Kubernetes operations Thin coverage/ })).toBeVisible(); });
test("3. inspects evidence and reasons", async ({ page }) => { await openGaps(page); await selectGap(page, /Kubernetes operations/); const detail = page.getByRole("complementary", { name: "Knowledge gap details" }); await expect(detail.getByRole("heading", { name: "Why flagged" })).toBeVisible(); await expect(detail.getByText("Referenced in 8 notes")).toBeVisible(); await expect(detail.getByText("Existing coverage")).toBeVisible(); });
test("4. opens a relevant canonical source", async ({ page }) => { await openGaps(page); await selectGap(page, /Kubernetes operations/); await page.getByRole("complementary", { name: "Knowledge gap details" }).getByRole("button", { name: /Library architecture/ }).click(); await expect(page.getByRole("heading", { name: "Library architecture", exact: true }).first()).toBeVisible(); });
test("5. views Fragmented Coverage", async ({ page }) => { await openGaps(page); await expect(page.getByRole("button", { name: /PostgreSQL transactions Fragmented knowledge/ })).toBeVisible(); });
test("6. views Missing Project Overview", async ({ page }) => { await openGaps(page); await expect(page.getByRole("button", { name: /Projects Possible missing overview/ })).toBeVisible(); });
test("7. views Recurring Open Questions", async ({ page }) => { await openGaps(page); await expect(page.getByRole("button", { name: /Offline conflict resolution Recurring unresolved topic/ })).toBeVisible(); });
test("8. views Missing Bridge Knowledge", async ({ page }) => { await openGaps(page); await expect(page.getByRole("button", { name: /Kubernetes and PostgreSQL Possible bridge explanation missing/ })).toBeVisible(); });
test("9. Concept Page has a coverage section linked to Gap Finder", async ({ page }) => { await mockSlate(page); await connect(page); await openKubernetes(page); const section = page.locator("#concept-coverage"); await expect(section.getByRole("heading", { name: "Coverage observations" })).toBeVisible(); await section.getByRole("button", { name: /Open Gap Finder/ }).click(); await expect(page.getByRole("heading", { name: "Knowledge Gaps", exact: true })).toBeVisible(); });
test("10. Project Brain has a compact gaps section", async ({ page }) => { await mockSlate(page); await connect(page); await openProject(page); const section = page.locator("#project-gaps"); await expect(section.getByRole("heading", { name: "Knowledge Gaps" })).toBeVisible(); await expect(section.getByRole("button", { name: /coverage observations in this project/ })).toBeVisible(); });
test("11. Library Health routes a coverage item to Gap Finder", async ({ page }) => { await mockSlate(page); await connect(page); await page.keyboard.press("Control+Shift+P"); await page.getByRole("combobox").fill("> library health"); await page.getByRole("option").filter({ hasText: "Library Health" }).first().click(); await page.getByRole("button", { name: /Thin concept coverage/ }).click(); await page.getByRole("complementary", { name: "Maintenance item details" }).getByRole("button", { name: /Review/ }).click(); await expect(page.getByRole("heading", { name: "Knowledge Gaps", exact: true })).toBeVisible(); });
test("12. asks Slate about a selected gap", async ({ page }) => { await openGaps(page); await selectGap(page, /Kubernetes operations/); await page.getByRole("complementary", { name: "Knowledge gap details" }).getByRole("button", { name: "Ask Slate" }).click(); await expect(page.getByRole("heading", { name: "Ask Slate", exact: true })).toBeVisible(); await expect(page.getByLabel("Question", { exact: true })).toHaveValue(/coverage weak/); });
test("13. creates an editable browser-local draft", async ({ page }) => { await openGaps(page); await selectGap(page, /Kubernetes operations/); await page.getByRole("button", { name: "Create Draft" }).click(); const dialog = page.getByRole("dialog", { name: "Kubernetes operations" }); await expect(dialog.getByLabel("Knowledge gap draft")).toHaveValue(/## What I Know/); await expect(dialog.getByLabel("Knowledge gap draft")).toHaveValue(/\[\[Projects\/Library architecture\]\]/); });
test("14. draft creation never saves a canonical note", async ({ page }) => { const state = await mockSlate(page); await connect(page); await page.keyboard.press("Control+Shift+P"); await page.getByRole("combobox").fill("> knowledge gaps"); await page.getByRole("option").filter({ hasText: "Knowledge Gaps" }).first().click(); await selectGap(page, /Kubernetes operations/); const before = state.requests.filter((request) => request.path.startsWith("v1/notes") && ["POST", "PUT"].includes(request.method)).length; await page.getByRole("button", { name: "Create Draft" }).click(); await page.getByLabel("Knowledge gap draft").fill("# Browser only\n\nEdited locally."); await page.getByRole("button", { name: "Done" }).click(); expect(state.requests.filter((request) => request.path.startsWith("v1/notes") && ["POST", "PUT"].includes(request.method))).toHaveLength(before); });
test("15. dismisses a gap", async ({ page }) => { await openGaps(page); await selectGap(page, /Kubernetes operations/); await page.getByRole("button", { name: "Dismiss", exact: true }).click(); await expect(page.locator(".gap-list").getByRole("button", { name: /Kubernetes operations/ })).toHaveCount(0); });
test("16. dismissal persists after leaving and reopening", async ({ page }) => { await openGaps(page); await selectGap(page, /Kubernetes operations/); await page.getByRole("button", { name: "Dismiss", exact: true }).click(); await page.keyboard.press("Control+Shift+P"); await page.getByRole("combobox").fill("> library"); await page.getByRole("option").filter({ hasText: /^Library$/ }).first().click(); await page.keyboard.press("Control+Shift+P"); await page.getByRole("combobox").fill("> knowledge gaps"); await page.getByRole("option").filter({ hasText: "Knowledge Gaps" }).first().click(); await expect(page.locator(".gap-list").getByRole("button", { name: /Kubernetes operations/ })).toHaveCount(0); });
test("17. keeps fragmented knowledge intentionally fragmented", async ({ page }) => { await openGaps(page); await selectGap(page, /PostgreSQL transactions/); await page.getByRole("button", { name: "Keep fragmented" }).click(); await expect(page.locator(".gap-list").getByRole("button", { name: /PostgreSQL transactions/ })).toHaveCount(0); });
test("18. deterministic flow works with generation disabled", async ({ page }) => { await openGaps(page, { generationEnabled: false }); await expect(page.getByRole("button", { name: /Kubernetes operations/ })).toBeVisible(); });
test("19. semantic-disabled flow is explicit and functional", async ({ page }) => { await openGaps(page, { semanticEnabled: false }); await expect(page.getByRole("status")).toContainText("semantic enrichment is unavailable"); await expect(page.getByRole("button", { name: /Kubernetes operations/ })).toBeVisible(); });
test("20. PostgreSQL fallback is explicit and functional", async ({ page }) => { await openGaps(page, { postgresAvailable: false }); await expect(page.getByRole("status")).toContainText("PostgreSQL persistence is unavailable"); await expect(page.getByRole("button", { name: /Kubernetes operations/ })).toBeVisible(); });
test("21. mobile gap list remains a single column without overflow", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await openGaps(page); await expect(page.getByRole("button", { name: /Kubernetes operations/ })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); });
test("22. mobile detail uses a full-screen review surface", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await openGaps(page); await selectGap(page, /Kubernetes operations/); const detail = page.getByRole("complementary", { name: "Knowledge gap details" }); await expect(detail).toBeVisible(); expect(await detail.evaluate((element) => Math.abs(element.getBoundingClientRect().width - innerWidth) < 2)).toBe(true); });
test("23. mobile draft preview is full screen and editable", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await openGaps(page); await selectGap(page, /Kubernetes operations/); await page.getByRole("button", { name: "Create Draft" }).click(); const dialog = page.getByRole("dialog", { name: "Kubernetes operations" }); await expect(dialog).toBeVisible(); expect(await dialog.evaluate((element) => Math.abs(element.getBoundingClientRect().width - innerWidth) < 2)).toBe(true); });
test("24. desktop Knowledge Gaps passes axe", async ({ page }) => { await openGaps(page); expect((await new AxeBuilder({ page }).include(".gap-workspace").analyze()).violations).toEqual([]); });
test("25. mobile Knowledge Gaps passes axe", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await openGaps(page); expect((await new AxeBuilder({ page }).include(".gap-workspace").analyze()).violations).toEqual([]); });
