import { test, expect, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { connect, mockSlate } from "./fixture";

async function openLinks(page: Page, generationEnabled = true) {
  await mockSlate(page, { generationEnabled }); await connect(page); await page.keyboard.press("Control+Shift+P"); await page.getByRole("combobox").fill("> link opportunities"); await page.getByRole("option").filter({ hasText: /^Link Opportunities/ }).click(); await expect(page.getByRole("heading", { name: "Link Opportunities" })).toBeVisible();
}
async function openFirstNote(page: Page) {
  await page.getByRole("treeitem", { name: "Projects", exact: true }).first().click(); await page.getByRole("treeitem", { name: "Library architecture", exact: true }).first().click(); await expect(page.getByRole("heading", { name: "Library architecture", exact: true }).first()).toBeVisible();
}
function direct(page: Page) { return page.getByRole("listitem").filter({ hasText: "Direct mention" }).first(); }

test("opens Link Opportunities from Command Center", async ({ page }) => { await openLinks(page); await expect(direct(page)).toBeVisible(); });
test("shows direct title or alias mention with preview", async ({ page }) => { await openLinks(page); await expect(direct(page)).toContainText("Exact alias match"); await expect(direct(page)).toContainText("[[Reading list|stable identities]]"); });
test("authored links are not repeated as suggestions", async ({ page }) => { await openLinks(page); await expect(page.getByText("Review [[Reading list]]", { exact: false })).toHaveCount(0); });
test("shows graph relationship evidence", async ({ page }) => { await openLinks(page); await expect(page.getByRole("listitem").filter({ hasText: "Graph relationship" })).toContainText("Two-hop authored graph path"); });
test("shows project relationships", async ({ page }) => { await openLinks(page); await expect(page.getByRole("listitem").filter({ hasText: "Project relationship" })).toContainText("Same project"); });
test("opens the source note", async ({ page }) => { await openLinks(page); await direct(page).getByRole("button", { name: "Open source" }).click(); await expect(page.getByRole("heading", { name: "Library architecture", exact: true }).first()).toBeVisible(); });
test("opens the target note", async ({ page }) => { await openLinks(page); await direct(page).getByRole("button", { name: "Open target" }).click(); await expect(page.getByRole("heading", { name: "Reading list", exact: true }).first()).toBeVisible(); });
test("inserts a suggestion into only the current editor draft", async ({ page }) => { await mockSlate(page); await connect(page); await openFirstNote(page); await page.getByRole("button", { name: /link opportunities for this note/i }).click(); await page.getByRole("dialog").getByRole("button", { name: "Insert link" }).click(); await page.keyboard.press("Escape"); await expect(page.getByText("Unsaved changes", { exact: true })).toBeVisible(); await expect(page.locator(".cm-content")).toContainText("[[Reading list|stable identities]]"); });
test("normal Save remains responsible after insertion", async ({ page }) => { await mockSlate(page); await connect(page); await openFirstNote(page); await page.getByRole("button", { name: /link opportunities for this note/i }).click(); await page.getByRole("dialog").getByRole("button", { name: "Insert link" }).click(); await page.keyboard.press("Escape"); await page.getByRole("button", { name: "Save note" }).click(); await expect(page.getByText("Saved", { exact: true })).toBeVisible(); });
test("changed source blocks a stale insertion", async ({ page }) => { await mockSlate(page); await connect(page); await openFirstNote(page); await page.getByRole("button", { name: "Write" }).click(); const editor = page.locator(".cm-content"); await editor.click(); await page.keyboard.press("Control+End"); await page.keyboard.type(" changed"); await page.getByRole("button", { name: /link opportunities for this note/i }).click(); await page.getByRole("dialog").getByRole("button", { name: "Insert link" }).click(); await expect(page.getByRole("alert")).toContainText("Text changed since this suggestion was generated"); });
test("dismisses a suggestion", async ({ page }) => { await openLinks(page); await direct(page).getByRole("button", { name: "Dismiss" }).click(); await expect(direct(page)).toHaveCount(0); });
test("dismissal survives reload", async ({ page }) => { await openLinks(page); await direct(page).getByRole("button", { name: "Dismiss" }).click(); await page.reload(); await expect(direct(page)).toHaveCount(0); await page.getByLabel("Review").selectOption("dismissed"); await expect(direct(page)).toBeVisible(); });
test("duplicate pairs are not presented as ordinary link suggestions", async ({ page }) => { await openLinks(page); await expect(page.getByText("Exact duplicate", { exact: true })).toHaveCount(0); await expect(page.getByText("Near duplicate", { exact: true })).toHaveCount(0); });
test("Knowledge Issue warning is explicit", async ({ page }) => { await openLinks(page); const item = page.getByRole("listitem").filter({ hasText: "currently disagree" }); await expect(item).toBeVisible(); await expect(item.getByRole("button", { name: "Review issue" })).toBeVisible(); });
test("better-target review is distinct", async ({ page }) => { await openLinks(page); const item = page.getByRole("listitem").filter({ hasText: "Better target" }); await expect(item).toContainText("older note"); await expect(item).toContainText("[[Reading list|Original architecture]]"); });
test("current-note command opens its suggestion panel", async ({ page }) => { await mockSlate(page); await connect(page); await openFirstNote(page); await page.keyboard.press("Control+Shift+P"); await page.getByRole("combobox").fill("> check current note for missing links"); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog", { name: "Link opportunities" })).toBeVisible(); });
test("Project Brain includes Relationship Opportunities", async ({ page }) => { await mockSlate(page); await connect(page); await page.getByRole("button", { name: "Actions for Projects" }).first().click(); await page.getByRole("menuitem", { name: "Open Project Brain" }).click(); await expect(page.getByRole("heading", { name: "Relationship Opportunities" })).toBeVisible(); await page.getByRole("button", { name: "Review relationships" }).click(); await expect(page.getByRole("heading", { name: "Link Opportunities" })).toBeVisible(); });
test("Inbox surfaces likely target notes", async ({ page }) => { await mockSlate(page); await connect(page); await page.getByRole("button", { name: "Inbox", exact: true }).first().click(); await expect(page.getByText(/likely target notes?/)).toBeVisible(); await page.getByText(/likely target notes?/).click(); await expect(page.getByRole("heading", { name: "Link Opportunities" })).toBeVisible(); });
test("generation-disabled flow remains useful", async ({ page }) => { await openLinks(page, false); await expect(page.getByText(/no generation provider is required/)).toBeVisible(); await expect(direct(page)).toBeVisible(); });
test("Ask is scoped to the relationship pair", async ({ page }) => { await openLinks(page); await direct(page).getByRole("button", { name: "Ask" }).click(); await expect(page.getByLabel("Question", { exact: true })).toHaveValue(/would linking them improve navigation/); });
test("suggested graph edges are disabled by default and visually distinct", async ({ page }) => { await mockSlate(page); await connect(page); await openFirstNote(page); await page.getByRole("button", { name: "Note graph" }).click(); await expect(page.locator(".graph-suggested-edge")).toHaveCount(0); await page.getByRole("checkbox", { name: "Suggested" }).check(); await expect(page.locator(".graph-suggested-edge").first()).toBeVisible(); });
test("mobile opens a usable suggestion sheet", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await mockSlate(page); await connect(page); await openFirstNote(page); await page.getByRole("button", { name: /link opportunities for this note/i }).click(); await expect(page.getByRole("dialog", { name: "Link opportunities" })).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); });
test("mobile insertion marks the draft unsaved", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await mockSlate(page); await connect(page); await openFirstNote(page); await page.getByRole("button", { name: /link opportunities for this note/i }).click(); await page.getByRole("dialog").getByRole("button", { name: "Insert link" }).click(); await page.keyboard.press("Escape"); await expect(page.getByText("Unsaved changes", { exact: true })).toBeVisible(); });
test("desktop Link Opportunities passes axe", async ({ page }) => { await openLinks(page); expect((await new AxeBuilder({ page }).include(".link-workspace").analyze()).violations).toEqual([]); });
test("mobile Link Opportunities passes axe", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await openLinks(page); expect((await new AxeBuilder({ page }).include(".link-workspace").analyze()).violations).toEqual([]); });
