import type { Note } from "@/lib/api/contracts";
import { conceptHash, normalizeConcept, type KnowledgeConcept } from "./concepts";
import { extractKnowledgeClaims, type KnowledgeIssue } from "./knowledge-issues";
import type { KnowledgeOverlap } from "./overlap";
import { deriveProjectSections } from "./project-brain";
import type { LinkSuggestion } from "./smart-links";

export const KNOWLEDGE_GAP_SCHEMA_VERSION = 1;
export const KNOWLEDGE_GAP_LIMITS = {
  maxNotes: 240, maxConcepts: 500, maxMembersPerConcept: 24, maxProjects: 80,
  maxNotesPerProject: 40, maxRelationshipsPerConcept: 12, maxQuestionsPerConcept: 12,
  maxBridgeFindings: 24, maxFindings: 240, defaultPageSize: 20, maxPageSize: 50,
  sourceConcurrency: 6, cacheMs: 60_000, healthItems: 40,
} as const;

export type KnowledgeGapKind = "thin-coverage" | "fragmented-coverage" | "missing-overview" | "missing-architecture-explanation" | "missing-decision-rationale" | "missing-operational-explanation" | "missing-failure-recovery-knowledge" | "recurring-unanswered-question" | "missing-bridge-knowledge" | "integration-gap";
export type GapCoverageLevel = "thin" | "fragmented" | "missing" | "limited";
export type GapImportance = "high" | "medium" | "low";
export type GapReviewState = "open" | "addressed" | "dismissed" | "not-relevant" | "intentionally-fragmented";
export type GapAction = "review-sources" | "create-draft" | "review-overlap" | "link-existing" | "answer-question" | "project-review";
export type GapWorkspace = "knowledge-gaps" | "concepts" | "project-brain" | "knowledge-overlap" | "link-opportunities" | "knowledge-issues" | "note";

export interface GapCoverageSource { noteId: string; title: string; path: string; revision: string; excerpt: string; explanatoryWords: number; substantial: boolean; }
export interface KnowledgeGap {
  id: string; libraryId: string; kind: KnowledgeGapKind; conceptId: string | null; conceptName: string | null; projectPath: string | null;
  noteIds: string[]; sourceConceptIds: string[]; title: string; summary: string; evidence: GapCoverageSource[]; signals: string[];
  coverageLevel: GapCoverageLevel; importanceLevel: GapImportance; recommendedActionType: GapAction; targetWorkspace: GapWorkspace;
  targetPayload: Record<string, string>; fingerprint: string; reviewState: GapReviewState; schemaVersion: number;
}
export interface GapFilters { page?: number; limit?: number; kind?: KnowledgeGapKind; project?: string; concept?: string; importance?: GapImportance; status?: GapReviewState; search?: string; selected?: string; }
export interface GapReviews { gaps?: Record<string, { state: GapReviewState }> }
export interface GapDiagnostics { conceptsAnalyzed: number; projectsAnalyzed: number; openGaps: number; thinCoverage: number; fragmentedCoverage: number; missingOverview: number; bridgeGaps: number; recurringQuestions: number; deterministicFindings: number; optionalModelClassifications: number; cacheHits: number; pending: number; failed: number; boundsReached: boolean; semanticAvailable: boolean; postgresAvailable: boolean; }
export interface KnowledgeGapResponse { schemaVersion: number; generatedAt: string; page: number; pageSize: number; total: number; items: KnowledgeGap[]; summary: { open: number; kinds: Partial<Record<KnowledgeGapKind, number>>; importance: Record<GapImportance, number> }; projects: string[]; concepts: Array<{ id: string; name: string }>; diagnostics: GapDiagnostics; degraded?: string; }
export interface GapAnalysisInput { libraryId?: string; notes: Note[]; concepts: KnowledgeConcept[]; issues?: KnowledgeIssue[]; overlaps?: KnowledgeOverlap[]; linkSuggestions?: LinkSuggestion[]; generatedAt?: string; semanticAvailable?: boolean; postgresAvailable?: boolean; failed?: number; pending?: number; conceptScopeIds?: string[]; projectScopePaths?: string[]; }

const kindLabels: Record<KnowledgeGapKind, string> = { "thin-coverage": "Thin coverage", "fragmented-coverage": "Fragmented knowledge", "missing-overview": "Possible missing overview", "missing-architecture-explanation": "Architecture coverage gap", "missing-decision-rationale": "Decision rationale gap", "missing-operational-explanation": "Operational coverage gap", "missing-failure-recovery-knowledge": "Possible resilience documentation gap", "recurring-unanswered-question": "Recurring unresolved topic", "missing-bridge-knowledge": "Possible bridge explanation missing", "integration-gap": "Integration gap" };
const importanceRank: Record<GapImportance, number> = { high: 0, medium: 1, low: 2 };
const stopWords = new Set(["a", "an", "and", "are", "can", "do", "does", "for", "how", "in", "is", "it", "of", "on", "or", "should", "the", "this", "to", "what", "when", "where", "which", "why", "with", "would"]);
function hash(value: string) { return conceptHash(value); }
function projectPath(path: string) { const parts = path.replace(/\\/g, "/").split("/"); return parts.length > 1 ? parts.slice(0, Math.min(2, parts.length - 1)).join("/") : null; }
function metadata(markdown: string) { const match = markdown.match(/^---\s*\r?\n([\s\S]*?)\r?\n---\s*(?:\r?\n|$)/); const fields: Record<string, string> = {}; for (const line of (match?.[1] ?? "").split(/\r?\n/)) { const pair = line.match(/^([A-Za-z][\w-]*):\s*(.*?)\s*$/); if (pair) fields[pair[1].toLowerCase()] = pair[2].replace(/^['"]|['"]$/g, ""); } return { fields, body: match ? markdown.slice(match[0].length) : markdown }; }
function clean(markdown: string) { return metadata(markdown).body.replace(/```[\s\S]*?```/g, " ").replace(/`[^`\n]+`/g, " ").replace(/^\s*>.*$/gm, " ").replace(/^\s*(?:at\s+\S+|(?:\w*(?:Exception|Error)|Error):).+$/gm, " ").replace(/https?:\/\/\S+/g, " "); }
function words(value: string) { return value.match(/[\p{L}\p{N}][\p{L}\p{N}+.#-]*/gu)?.length ?? 0; }
function excluded(note: Note) { const path = note.path.replace(/\\/g, "/").toLowerCase(), type = metadata(note.markdown).fields.type?.toLowerCase(); return /(^|\/)(daily|inbox|templates?|\.slate)(\/|$)/.test(path) || ["daily", "template", "log", "system"].includes(type ?? ""); }
function sections(markdown: string) { const body = clean(markdown), matches = [...body.matchAll(/^#{1,4}\s+(.+?)\s*#*$/gm)]; if (!matches.length) return [{ heading: "", text: body }]; return matches.map((match, index) => ({ heading: match[1], text: body.slice(match.index!, matches[index + 1]?.index ?? body.length) })); }
function tokens(value: string) { return [...new Set(normalizeConcept(value).split(/\s+/).filter((token) => token.length > 2 && !stopWords.has(token)))]; }
function overlap(a: string[], b: string[]) { const right = new Set(b); return a.filter((item) => right.has(item)).length / Math.max(1, Math.min(a.length, b.length)); }
function evidenceFor(note: Note, concept: KnowledgeConcept): GapCoverageSource {
  const aliases = [concept.canonicalName, ...concept.aliases].map(normalizeConcept).filter(Boolean), title = normalizeConcept(note.title), member = concept.members.find((item) => item.noteId === note.id)!;
  const relevant = sections(note.markdown).filter((section) => aliases.some((alias) => normalizeConcept(`${section.heading} ${section.text}`).includes(alias)));
  const dedicated = aliases.some((alias) => title === alias); const explanatoryWords = Math.min(1_200, words((dedicated ? clean(note.markdown) : relevant.map((section) => section.text).join(" ")) || member.excerpt));
  const substantial = explanatoryWords >= 120 && (dedicated || relevant.some((section) => aliases.some((alias) => normalizeConcept(section.heading).includes(alias))) || member.decisions.length > 0);
  return { noteId: note.id, title: note.title, path: note.path, revision: note.revision, excerpt: member.excerpt.slice(0, 360), explanatoryWords, substantial };
}
function reviewState(fingerprint: string, reviews: GapReviews) { return reviews.gaps?.[fingerprint]?.state ?? "open"; }
function createGap(input: Omit<KnowledgeGap, "id" | "libraryId" | "reviewState" | "schemaVersion">, libraryId: string, reviews: GapReviews): KnowledgeGap { const fingerprint = `v${KNOWLEDGE_GAP_SCHEMA_VERSION}:${input.fingerprint}`; return { ...input, fingerprint, id: `gap-${hash(fingerprint)}`, libraryId, reviewState: reviewState(fingerprint, reviews), schemaVersion: KNOWLEDGE_GAP_SCHEMA_VERSION }; }
function evidenceSignature(values: GapCoverageSource[]) { return values.map((value) => `${value.noteId}:${hash(`${value.excerpt}|${value.explanatoryWords}|${value.substantial}`)}`).sort().join("|"); }
function importance(concept: KnowledgeConcept) { const decisions = concept.members.reduce((sum, member) => sum + member.decisions.length, 0); return concept.projectPaths.length > 1 || concept.sourceCount >= 8 || decisions > 0 || concept.openQuestionCount > 1 ? "high" : concept.sourceCount >= 4 ? "medium" : "low"; }
function projectAreas(notes: Note[]) { const values = new Set<string>(); const rules: Array<[string, RegExp]> = [["API", /\b(api|endpoint|controller|route)\b/i], ["data", /\b(database|storage|schema|postgres|redis)\b/i], ["deployment", /\b(deploy|docker|kubernetes|k3s|cloudflare|nodeport)\b/i], ["integration", /\b(sync|integration|webhook|queue|tunnel)\b/i], ["interface", /\b(ui|ux|frontend|mobile|web client)\b/i], ["testing", /\b(test|verification|playwright|vitest)\b/i], ["operations", /\b(backup|restore|rollback|monitor|incident|recovery)\b/i]]; for (const note of notes) { const value = `${note.path} ${note.title} ${clean(note.markdown).slice(0, 4_000)}`; for (const [name, pattern] of rules) if (pattern.test(value)) values.add(name); } return values; }
function projectEvidence(notes: Note[], pattern: RegExp) { return notes.filter((note) => pattern.test(`${note.path} ${note.title} ${clean(note.markdown).slice(0, 4_000)}`)).slice(0, 12).map((note): GapCoverageSource => ({ noteId: note.id, title: note.title, path: note.path, revision: note.revision, excerpt: clean(note.markdown).trim().slice(0, 360), explanatoryWords: words(clean(note.markdown)), substantial: words(clean(note.markdown)) >= 120 })); }
function clusteredQuestions(concept: KnowledgeConcept) { const questions = concept.members.flatMap((member) => member.questions.map((text) => ({ text, member }))).slice(0, KNOWLEDGE_GAP_LIMITS.maxQuestionsPerConcept); let best: typeof questions = []; for (const seed of questions) { const seedTokens = tokens(seed.text); const cluster = questions.filter((candidate) => overlap(seedTokens, tokens(candidate.text)) >= .3); if (cluster.length > best.length) best = cluster; } return best; }

export function analyzeKnowledgeGaps(input: GapAnalysisInput, reviews: GapReviews = {}): { gaps: KnowledgeGap[]; diagnostics: Omit<GapDiagnostics, "openGaps" | "cacheHits">; generatedAt: string; degraded?: string } {
  const libraryId = input.libraryId ?? "session", notes = input.notes.filter((note) => !excluded(note)).slice(0, KNOWLEDGE_GAP_LIMITS.maxNotes), byId = new Map(notes.map((note) => [note.id, note])), results: KnowledgeGap[] = [];
  const allConcepts = input.concepts.slice(0, KNOWLEDGE_GAP_LIMITS.maxConcepts), conceptScope = input.conceptScopeIds ? new Set(input.conceptScopeIds) : null, concepts = conceptScope ? allConcepts.filter((concept) => conceptScope.has(concept.id)) : allConcepts, overlaps = input.overlaps ?? [], links = input.linkSuggestions ?? [], issues = input.issues ?? [];
  for (const concept of concepts) {
    const members = concept.members.slice(0, KNOWLEDGE_GAP_LIMITS.maxMembersPerConcept).flatMap((member) => byId.get(member.noteId) ? [evidenceFor(byId.get(member.noteId)!, concept)] : []);
    const meaningful = members.filter((member) => member.explanatoryWords >= 18), substantial = members.filter((member) => member.substantial), totalWords = meaningful.reduce((sum, member) => sum + member.explanatoryWords, 0), collectiveCoverage = meaningful.filter((member) => member.explanatoryWords >= 70).length >= 3 && totalWords >= 360, incidental = concept.sourceCount < 3 || members.filter((member) => member.explanatoryWords > 8).length < 2;
    const libraryLike = ["Library", "Framework", "Language"].includes(concept.kind), important = importance(concept);
    if (!incidental && !substantial.length && !collectiveCoverage && (!libraryLike || concept.sourceCount >= 6)) {
      const fragmented = members.length >= 4 && meaningful.length >= 3 && totalWords >= 180; const kind: KnowledgeGapKind = fragmented ? "fragmented-coverage" : "thin-coverage";
      if (fragmented || concept.sourceCount >= 4 || concept.projectPaths.length > 1) {
        const relatedOverlap = overlaps.find((finding) => members.some((member) => member.noteId === finding.noteA.noteId) && members.some((member) => member.noteId === finding.noteB.noteId));
        const fingerprint = `${kind}:${concept.id}:${evidenceSignature(members)}`;
        results.push(createGap({ kind, conceptId: concept.id, conceptName: concept.canonicalName, projectPath: concept.projectPaths.length === 1 ? concept.projectPaths[0] : null, noteIds: members.map((member) => member.noteId), sourceConceptIds: [concept.id], title: concept.canonicalName, summary: fragmented ? `Knowledge about ${concept.canonicalName} appears across ${members.length} brief sources without one substantial explanation.` : `${concept.canonicalName} is referenced across ${concept.sourceCount} notes${concept.projectPaths.length ? ` and ${concept.projectPaths.length} project${concept.projectPaths.length === 1 ? "" : "s"}` : ""}, but current explanations are limited.`, evidence: members, signals: [`Referenced in ${concept.sourceCount} notes`, ...(concept.projectPaths.length ? [`Appears in ${concept.projectPaths.length} projects`] : []), `${substantial.length} substantial explanatory sources`, ...(fragmented ? [`Fragmented across ${meaningful.length} brief sources`] : [])], coverageLevel: fragmented ? "fragmented" : "thin", importanceLevel: important, recommendedActionType: relatedOverlap ? "review-overlap" : "create-draft", targetWorkspace: relatedOverlap ? "knowledge-overlap" : "concepts", targetPayload: relatedOverlap ? { noteId: relatedOverlap.noteA.noteId, fingerprint: relatedOverlap.fingerprint } : { concept: concept.canonicalName }, fingerprint }, libraryId, reviews));
      }
    }
    const questions = clusteredQuestions({ ...concept, members: concept.members.filter((member) => byId.has(member.noteId)) }), answeredIds = new Set(issues.filter((issue) => issue.kind === "answered-question").flatMap((issue) => [issue.sourceA.noteId, issue.sourceB.noteId]));
    if (questions.length >= 2 && questions.filter((question) => !answeredIds.has(question.member.noteId)).length >= 2) {
      const questionEvidence = questions.map(({ text, member }): GapCoverageSource => ({ noteId: member.noteId, title: member.title, path: member.path, revision: member.revision, excerpt: text.slice(0, 360), explanatoryWords: words(text), substantial: false }));
      const fingerprint = `recurring-question:${concept.id}:${evidenceSignature(questionEvidence)}`;
      results.push(createGap({ kind: "recurring-unanswered-question", conceptId: concept.id, conceptName: concept.canonicalName, projectPath: concept.projectPaths.length === 1 ? concept.projectPaths[0] : null, noteIds: questionEvidence.map((value) => value.noteId), sourceConceptIds: [concept.id], title: concept.canonicalName, summary: `${questions.length} unresolved questions describe a recurring topic around ${concept.canonicalName}.`, evidence: questionEvidence, signals: [`${questions.length} related open questions`, "No later answer was identified by Knowledge Issues"], coverageLevel: "limited", importanceLevel: important === "low" ? "medium" : important, recommendedActionType: "answer-question", targetWorkspace: "knowledge-issues", targetPayload: { noteId: questionEvidence[0].noteId }, fingerprint }, libraryId, reviews));
    }
  }
  const conceptById = new Map(concepts.map((concept) => [concept.id, concept])); const bridgeKeys = new Set<string>(); let bridgeCount = 0;
  for (const concept of concepts) for (const relationship of concept.relationships.slice(0, KNOWLEDGE_GAP_LIMITS.maxRelationshipsPerConcept)) {
    const target = conceptById.get(relationship.targetConceptId), key = [concept.id, relationship.targetConceptId].sort().join("|"); if (!target || bridgeKeys.has(key) || bridgeCount >= KNOWLEDGE_GAP_LIMITS.maxBridgeFindings || relationship.sourceCount < 2 || (concept.sourceCount < 3 && target.sourceCount < 3)) continue; bridgeKeys.add(key);
    const shared = relationship.sourceNoteIds.flatMap((id) => byId.get(id) ? [byId.get(id)!] : []), bridgeExists = shared.some((note) => evidenceFor(note, concept).substantial && evidenceFor(note, target).substantial && /\b(connect|flow|interact|integrat|depend|request path|architecture)\b/i.test(clean(note.markdown)));
    if (bridgeExists) continue; const suggestion = links.find((item) => concept.members.some((member) => member.noteId === item.sourceNoteId) && target.members.some((member) => member.noteId === item.target.noteId)); const evidence = shared.map((note) => evidenceFor(note, concept)); const fingerprint = `bridge:${key}:${evidenceSignature(evidence)}`;
    results.push(createGap({ kind: suggestion ? "integration-gap" : "missing-bridge-knowledge", conceptId: concept.id, conceptName: concept.canonicalName, projectPath: relationship.projectCount === 1 ? concept.projectPaths.find((path) => target.projectPaths.includes(path)) ?? null : null, noteIds: relationship.sourceNoteIds.slice(0, 12), sourceConceptIds: [concept.id, target.id], title: `${concept.canonicalName} and ${target.canonicalName}`, summary: suggestion ? "Relevant knowledge exists, but the authored relationship is missing." : `These concepts repeatedly appear together, but no substantial source explains how ${concept.canonicalName} and ${target.canonicalName} interact.`, evidence, signals: relationship.signals.slice(0, 4), coverageLevel: "missing", importanceLevel: relationship.projectCount > 1 || relationship.sourceCount >= 4 ? "high" : "medium", recommendedActionType: suggestion ? "link-existing" : "create-draft", targetWorkspace: suggestion ? "link-opportunities" : "concepts", targetPayload: suggestion ? { noteId: suggestion.sourceNoteId, fingerprint: suggestion.fingerprint } : { concept: concept.canonicalName }, fingerprint }, libraryId, reviews)); bridgeCount++;
  }
  const projects = new Map<string, Note[]>(); for (const note of notes) { const path = projectPath(note.path); if (path) projects.set(path, [...(projects.get(path) ?? []), note]); }
  const projectScope = input.projectScopePaths ? new Set(input.projectScopePaths) : null;
  for (const [path, projectNotesRaw] of [...projects].filter(([path]) => !projectScope || projectScope.has(path)).slice(0, KNOWLEDGE_GAP_LIMITS.maxProjects)) {
    const projectNotes = projectNotesRaw.slice(0, KNOWLEDGE_GAP_LIMITS.maxNotesPerProject); if (projectNotes.length < 6) continue; const areas = projectAreas(projectNotes), derived = deriveProjectSections(projectNotes), evidence = projectEvidence(projectNotes, /./), sourceSignature = evidenceSignature(evidence);
    const overviewStrong = derived.sections.overview.some((source) => words(source.excerpt) >= 120); if (areas.size >= 3 && !overviewStrong) { const fingerprint = `project-overview:${path}:${sourceSignature}`; results.push(createGap({ kind: "missing-overview", conceptId: null, conceptName: null, projectPath: path, noteIds: evidence.map((value) => value.noteId), sourceConceptIds: [], title: path.split("/").at(-1) ?? path, summary: `This project contains ${projectNotes.length} notes across ${areas.size} documented areas, but no substantial overview was found.`, evidence, signals: [`${projectNotes.length} project notes`, `Documented areas: ${[...areas].join(", ")}`, "No substantial README or overview source"], coverageLevel: "missing", importanceLevel: projectNotes.length >= 12 ? "high" : "medium", recommendedActionType: "create-draft", targetWorkspace: "project-brain", targetPayload: { project: path }, fingerprint }, libraryId, reviews)); }
    const componentHeavy = ["API", "data", "deployment", "integration"].filter((area) => areas.has(area)).length >= 3, architectureStrong = derived.sections.architecture.some((source) => words(source.excerpt) >= 120); if (componentHeavy && !architectureStrong) { const architectureEvidence = projectEvidence(projectNotes, /\b(api|database|storage|deploy|docker|kubernetes|sync|integration|tunnel|service)\b/i); const fingerprint = `project-architecture:${path}:${evidenceSignature(architectureEvidence)}`; results.push(createGap({ kind: "missing-architecture-explanation", conceptId: null, conceptName: null, projectPath: path, noteIds: architectureEvidence.map((value) => value.noteId), sourceConceptIds: [], title: `${path.split("/").at(-1) ?? path} architecture`, summary: "The project documents several components and dependencies, but no substantial architecture or request-flow explanation was found.", evidence: architectureEvidence, signals: [`Component areas: ${[...areas].filter((area) => ["API", "data", "deployment", "integration"].includes(area)).join(", ")}`, "No substantial architecture source"], coverageLevel: "missing", importanceLevel: "high", recommendedActionType: "create-draft", targetWorkspace: "project-brain", targetPayload: { project: path }, fingerprint }, libraryId, reviews)); }
    const decisions = projectNotes.flatMap((note) => extractKnowledgeClaims(note).filter((claim) => claim.claimType === "decision").map((claim) => ({ note, claim }))).slice(0, 12), unexplained = decisions.filter(({ note }) => !/\b(because|why|rationale|trade[- ]?off|chosen because|due to)\b/i.test(clean(note.markdown))); if (unexplained.length >= 2) { const decisionEvidence = unexplained.map(({ note, claim }): GapCoverageSource => ({ noteId: note.id, title: note.title, path: note.path, revision: note.revision, excerpt: claim.text.slice(0, 360), explanatoryWords: words(claim.text), substantial: false })); const fingerprint = `decision-rationale:${path}:${evidenceSignature(decisionEvidence)}`; results.push(createGap({ kind: "missing-decision-rationale", conceptId: null, conceptName: null, projectPath: path, noteIds: decisionEvidence.map((value) => value.noteId), sourceConceptIds: [], title: `${path.split("/").at(-1) ?? path} decisions`, summary: `${unexplained.length} documented decisions do not include nearby rationale or trade-off evidence.`, evidence: decisionEvidence, signals: [`${unexplained.length} important decision claims`, "No rationale markers in their source notes"], coverageLevel: "limited", importanceLevel: "medium", recommendedActionType: "review-sources", targetWorkspace: "project-brain", targetPayload: { project: path }, fingerprint }, libraryId, reviews)); }
    const operational = projectEvidence(projectNotes, /\b(deploy|production|kubernetes|k3s|docker|nodeport|cloudflare|database|postgres)\b/i), recovery = projectEvidence(projectNotes, /\b(backup|restore|recovery|rollback|failover|incident|postmortem|disaster)\b/i); if (operational.length >= 3 && !recovery.some((value) => value.substantial)) { const fingerprint = `failure-recovery:${path}:${evidenceSignature(operational)}`; results.push(createGap({ kind: "missing-failure-recovery-knowledge", conceptId: null, conceptName: null, projectPath: path, noteIds: operational.map((value) => value.noteId), sourceConceptIds: [], title: `${path.split("/").at(-1) ?? path} resilience`, summary: "Production or deployment material is present, but substantial backup, rollback, failure, or recovery guidance was not found.", evidence: operational, signals: [`${operational.length} operational sources`, "No substantial recovery or rollback source"], coverageLevel: "missing", importanceLevel: "high", recommendedActionType: "project-review", targetWorkspace: "project-brain", targetPayload: { project: path }, fingerprint }, libraryId, reviews)); }
  }
  const ordered = orderKnowledgeGaps(results); const bounded = input.notes.length > notes.length || input.concepts.length > allConcepts.length || ordered.length > KNOWLEDGE_GAP_LIMITS.maxFindings;
  const gaps = ordered.slice(0, KNOWLEDGE_GAP_LIMITS.maxFindings), semanticAvailable = input.semanticAvailable ?? false, postgresAvailable = input.postgresAvailable ?? false;
  return { gaps, generatedAt: input.generatedAt ?? new Date().toISOString(), diagnostics: { conceptsAnalyzed: concepts.length, projectsAnalyzed: [...projects].filter(([, values]) => values.length >= 6).length, thinCoverage: gaps.filter((gap) => gap.kind === "thin-coverage").length, fragmentedCoverage: gaps.filter((gap) => gap.kind === "fragmented-coverage").length, missingOverview: gaps.filter((gap) => gap.kind === "missing-overview").length, bridgeGaps: gaps.filter((gap) => gap.kind === "missing-bridge-knowledge" || gap.kind === "integration-gap").length, recurringQuestions: gaps.filter((gap) => gap.kind === "recurring-unanswered-question").length, deterministicFindings: gaps.length, optionalModelClassifications: 0, pending: input.pending ?? 0, failed: input.failed ?? 0, boundsReached: bounded, semanticAvailable, postgresAvailable }, degraded: !postgresAvailable ? "Knowledge gaps are available from bounded session analysis; PostgreSQL persistence is unavailable." : !semanticAvailable ? "Deterministic knowledge-gap analysis is active; semantic enrichment is unavailable." : undefined };
}

export function orderKnowledgeGaps(values: KnowledgeGap[]) { return [...values].sort((a, b) => importanceRank[a.importanceLevel] - importanceRank[b.importanceLevel] || b.signals.length - a.signals.length || b.noteIds.length - a.noteIds.length || a.title.localeCompare(b.title) || a.fingerprint.localeCompare(b.fingerprint)); }

export function pageKnowledgeGaps(analysis: ReturnType<typeof analyzeKnowledgeGaps>, filters: GapFilters = {}, reviews: GapReviews = {}, cacheHits = 0): KnowledgeGapResponse {
  const reviewed = analysis.gaps.map((gap) => ({ ...gap, reviewState: reviewState(gap.fingerprint, reviews) }));
  const visible = reviewed.filter((gap) => !filters.kind || gap.kind === filters.kind).filter((gap) => !filters.project || gap.projectPath === filters.project || gap.evidence.some((source) => source.path.startsWith(`${filters.project}/`))).filter((gap) => !filters.concept || gap.conceptId === filters.concept || gap.sourceConceptIds.includes(filters.concept) || gap.conceptName?.toLowerCase().includes(filters.concept.toLowerCase())).filter((gap) => !filters.importance || gap.importanceLevel === filters.importance).filter((gap) => !filters.status || gap.reviewState === filters.status).filter((gap) => !filters.search || `${gap.title} ${gap.summary} ${gap.signals.join(" ")} ${gap.evidence.map((source) => `${source.title} ${source.path}`).join(" ")}`.toLowerCase().includes(filters.search.toLowerCase()));
  const page = Math.max(0, Math.trunc(filters.page ?? 0)), pageSize = Math.min(KNOWLEDGE_GAP_LIMITS.maxPageSize, Math.max(1, Math.trunc(filters.limit ?? KNOWLEDGE_GAP_LIMITS.defaultPageSize))), start = page * pageSize, open = visible.filter((gap) => gap.reviewState === "open");
  const kinds: Partial<Record<KnowledgeGapKind, number>> = {}; for (const gap of open) kinds[gap.kind] = (kinds[gap.kind] ?? 0) + 1;
  return { schemaVersion: KNOWLEDGE_GAP_SCHEMA_VERSION, generatedAt: analysis.generatedAt, page, pageSize, total: visible.length, items: visible.slice(start, start + pageSize), summary: { open: open.length, kinds, importance: { high: open.filter((gap) => gap.importanceLevel === "high").length, medium: open.filter((gap) => gap.importanceLevel === "medium").length, low: open.filter((gap) => gap.importanceLevel === "low").length } }, projects: [...new Set(analysis.gaps.flatMap((gap) => gap.projectPath ? [gap.projectPath] : []))].sort(), concepts: [...new Map(analysis.gaps.flatMap((gap) => gap.conceptId && gap.conceptName ? [[gap.conceptId, { id: gap.conceptId, name: gap.conceptName }] as const] : [])).values()].sort((a, b) => a.name.localeCompare(b.name)), diagnostics: { ...analysis.diagnostics, openGaps: open.length, cacheHits }, degraded: analysis.degraded };
}

export function gapKindLabel(kind: KnowledgeGapKind) { return kindLabels[kind]; }
export function createGapDraft(gap: KnowledgeGap) {
  const related = gap.evidence.slice(0, 12).map((source) => `- [[${source.path.replace(/\.md$/i, "")}]]`).join("\n");
  const questions = gap.kind === "recurring-unanswered-question" ? gap.evidence.slice(0, 8).map((source) => `- ${source.excerpt}`).join("\n") : "- ";
  return `# ${gap.title}\n\n## What I Know\n\n\n## How It Works\n\n\n## Why It Matters\n\n\n## Related Notes\n\n${related || "- "}\n\n## Open Questions\n\n${questions}\n`;
}
