"use client";
import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowUpRight, Check, ChevronRight, CircleHelp, Clock3, FolderInput, Layers3, MessageCircleQuestion, MoreHorizontal, Plus, Search } from "lucide-react";
import { useApi } from "@/lib/auth/context";
import { useWorkspace } from "@/features/notes/workspace-context";
import { useInboxTriageReviews } from "@/lib/storage/inbox-triage-reviews";
import { drafts } from "@/lib/storage/drafts";
import type { InboxTriageAnalysis, InboxTriageSuggestion } from "@/lib/intelligence/inbox-triage";
import { Button } from "@/components/ui/button";
import { Empty, ErrorMessage, Loading, Modal } from "@/components/common/primitives";
import { FolderPicker } from "@/components/library/folder-picker";
import { BulkActions } from "@/components/library/bulk-actions";
import { openAskSlate } from "@/components/ask/ask-slate";

type Preview = { kind:"question"|"create"; item:InboxTriageAnalysis; folder:string; title:string; name:string; content:string } | { kind:"append"; item:InboxTriageAnalysis; targetId:string; targetRevision:string; targetContext:string; proposed:string; targetTitle:string; loading:boolean; error?:unknown };
const safeName = (value:string) => (value.trim().replace(/[\\/:*?"<>|]+/g,"-").replace(/\s+/g," ").slice(0,120) || "Inbox note") + ".md";
function entry(item:InboxTriageAnalysis) { return { id:item.captureId, title:item.title, name:item.path.split("/").at(-1) ?? item.title, path:item.path, isDirectory:false }; }
function typeLabel(item:InboxTriageAnalysis) { return `${item.suggestedType}${item.confidence === "strong" ? "" : ` · ${item.confidence}`}`; }

export function InboxTriage() {
  const api=useApi(), workspace=useWorkspace(), cache=useQueryClient(), local=useInboxTriageReviews(workspace.scope);
  const query=useQuery({ queryKey:["inbox-triage"], queryFn:({signal}) => api.inboxTriage(signal), staleTime:60_000 });
  const [selected,setSelected]=useState<string|null>(null), [filter,setFilter]=useState<"unprocessed"|"processed"|"deferred"|"all">("unprocessed"), [zero,setZero]=useState(() => typeof sessionStorage !== "undefined" && sessionStorage.getItem("slate.inbox-zero") === "1"), [checked,setChecked]=useState<string[]>([]), [preview,setPreview]=useState<Preview|null>(null), [busy,setBusy]=useState(false), [created,setCreated]=useState<{id:string;item:InboxTriageAnalysis}|null>(null), [error,setError]=useState<unknown>(null);
  useEffect(() => { sessionStorage.removeItem("slate.inbox-zero"); },[]);
  const all=useMemo(() => query.data?.items ?? [],[query.data?.items]);
  const visible=useMemo(() => all.filter((item) => filter === "all" || local.state(item.captureId,item.captureHash) === filter),[all,filter,local]);
  const current=visible.find((item) => item.captureId === selected) ?? visible[0] ?? null;
  useEffect(() => { if (current && selected !== current.captureId) setSelected(current.captureId); },[current,selected]);
  const advance=(item:InboxTriageAnalysis,state:"processed"|"deferred") => { local.setItem(item.captureId,item.captureHash,state); const index=visible.findIndex((value) => value.captureId === item.captureId); setSelected(visible[index+1]?.captureId ?? visible[index-1]?.captureId ?? null); };
  function action(item:InboxTriageAnalysis,suggestion:InboxTriageSuggestion) {
    if (suggestion.action === "keep") { local.setSuggestion(suggestion.fingerprint,"accepted"); advance(item,"processed"); return; }
    if (suggestion.action === "move") { local.setSuggestion(suggestion.fingerprint,"accepted"); workspace.setOperation({kind:"move",entry:entry(item),folder:suggestion.destination}); return; }
    if (suggestion.action === "append" && suggestion.targetNoteId) { void openAppend(item,suggestion.targetNoteId); return; }
    if (suggestion.action === "convert-question") { setPreview({kind:"question",item,folder:item.possibleFolders[0]?.path ?? "",title:item.title,name:safeName(item.title),content:item.content}); return; }
    if (suggestion.action === "create-note") { setPreview({kind:"create",item,folder:suggestion.destination ?? "",title:item.title,name:safeName(item.title),content:item.content}); return; }
  }
  async function openAppend(item:InboxTriageAnalysis,targetId:string) { setPreview({kind:"append",item,targetId,targetRevision:"",targetContext:"",proposed:"",targetTitle:"Loading target…",loading:true}); try { const target=await api.note(targetId); const proposed=`${target.markdown.trimEnd()}\n\n## Captured thought\n\n${item.content.trim()}\n`; setPreview({kind:"append",item,targetId,targetRevision:target.revision,targetContext:target.markdown.trim().slice(-600),proposed,targetTitle:target.title,loading:false}); } catch(error) { setPreview({kind:"append",item,targetId,targetRevision:"",targetContext:"",proposed:"",targetTitle:"Target unavailable",loading:false,error}); } }
  useEffect(() => {
    const handler=(event:KeyboardEvent) => { const target=event.target as HTMLElement|null; if (target?.matches("input, textarea, select, [contenteditable=true]") || preview) return; if (!["j","k","ArrowDown","ArrowUp","Enter","e","m","q","a","d"].includes(event.key)) return; if (!current) return; event.preventDefault(); const index=visible.findIndex((item) => item.captureId === current.captureId); if (event.key === "j" || event.key === "ArrowDown") setSelected(visible[Math.min(index+1,visible.length-1)]?.captureId ?? null); else if (event.key === "k" || event.key === "ArrowUp") setSelected(visible[Math.max(index-1,0)]?.captureId ?? null); else if (event.key === "Enter") workspace.open(current.captureId); else if (event.key === "e") advance(current,"processed"); else if (event.key === "m") workspace.setOperation({kind:"move",entry:entry(current),folder:current.possibleFolders[0]?.path}); else if (event.key === "q") { const suggestion=current.suggestedActions.find((item) => item.action === "convert-question"); if (suggestion) action(current,suggestion); } else if (event.key === "a") { const suggestion=current.suggestedActions.find((item) => item.action === "append"); if (suggestion) action(current,suggestion); } else if (event.key === "d") workspace.setOperation({kind:"delete",entry:entry(current)}); };
    addEventListener("keydown",handler); return () => removeEventListener("keydown",handler);
    // Keyboard handlers intentionally follow the currently rendered triage state.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[current,visible,preview]);
  if (query.isPending) return <div className="inbox-triage loading"><Loading label="Analyzing recent Inbox captures…" /></div>;
  if (query.error) return <div className="inbox-triage loading"><ErrorMessage error={query.error} retry={() => query.refetch()} /></div>;
  const unprocessed=all.filter((item) => local.state(item.captureId,item.captureHash) === "unprocessed").length;
  return <div className={`inbox-triage ${zero ? "inbox-zero" : ""}`}>
    <header className="inbox-triage-header"><div><span className="eyebrow">CAPTURE & ORGANIZE</span><h1>Inbox <small>{unprocessed}</small></h1><p>Review one thought at a time. Slate suggests; you decide.</p></div><div><Button variant="outline" onClick={() => setZero((value) => !value)}>{zero ? "Show queue" : "Inbox Zero"}</Button><Button onClick={() => workspace.setCaptureOpen(true)}><Plus size={15}/>Capture</Button></div></header>
    <div className="inbox-triage-toolbar"><label><Search size={14}/><select aria-label="Filter Inbox review state" value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)}><option value="unprocessed">Unprocessed</option><option value="processed">Processed</option><option value="deferred">Later</option><option value="all">All captures</option></select></label><span>{visible.length} shown</span><small>J/K navigate · Enter open · E keep · M move · Q question · A append</small></div>
    {query.data?.degraded && <p className="inbox-triage-degraded">{query.data.degraded}</p>}
    {checked.length > 0 && <div className="inbox-triage-bulk"><Button size="sm" onClick={() => { for (const id of checked) { const item=all.find((value) => value.captureId===id); if(item) local.setItem(id,item.captureHash,"processed"); } setChecked([]); }}>Mark processed</Button><Button size="sm" variant="outline" onClick={() => { for (const id of checked) { const item=all.find((value) => value.captureId===id); if(item) local.setItem(id,item.captureHash,"deferred"); } setChecked([]); }}>Later</Button><BulkActions paths={checked.map((id) => all.find((item) => item.captureId===id)?.path).filter(Boolean) as string[]} onDone={() => { setChecked([]); void query.refetch(); }} onCancel={() => setChecked([])}/></div>}
    {!current ? <Empty title={filter === "unprocessed" ? "Inbox reviewed" : "No captures in this view"} detail={filter === "unprocessed" ? "Processed captures remain available from the filter." : "Capture a thought or change the review filter."}/> : <div className="inbox-triage-body">
      {!zero && <ul className="inbox-triage-list scroll-area" aria-label="Inbox triage queue">{visible.map((item) => <li key={item.captureId} className={item.captureId===current.captureId ? "selected" : ""}><input type="checkbox" aria-label={`Select ${item.title}`} checked={checked.includes(item.captureId)} onChange={(event) => setChecked((values) => event.target.checked ? [...values,item.captureId] : values.filter((id) => id!==item.captureId))}/><button onClick={() => setSelected(item.captureId)}><strong>{item.title}</strong><small>{typeLabel(item)}{item.possibleProjects[0] ? ` · ${item.possibleProjects[0].path}` : ""}</small><p>{item.content}</p></button><ChevronRight size={15}/></li>)}</ul>}
      <TriageDetail item={{...current,suggestedActions:current.suggestedActions.filter((suggestion) => !local.reviews.suggestions[suggestion.fingerprint] || local.reviews.suggestions[suggestion.fingerprint].state === "accepted")}} remaining={unprocessed} zero={zero} state={local.state(current.captureId,current.captureHash)} onOpen={() => workspace.open(current.captureId)} onAction={(suggestion) => action(current,suggestion)} onKeep={() => advance(current,"processed")} onLater={() => advance(current,"deferred")} onDismiss={(suggestion) => local.setSuggestion(suggestion.fingerprint,"dismissed")} onNotRelevant={(suggestion) => local.setSuggestion(suggestion.fingerprint,"not-relevant")} onMove={() => workspace.setOperation({kind:"move",entry:entry(current),folder:current.possibleFolders[0]?.path})} onDelete={() => workspace.setOperation({kind:"delete",entry:entry(current)})} onRelated={(id) => workspace.open(id)} onOverlap={() => workspace.openKnowledgeOverlap({kind:"project",path:"inbox"})} onLinks={() => workspace.openLinkOpportunities({kind:"project",path:"inbox"})} onGap={(fingerprint) => workspace.openKnowledgeGaps({status:"open",selected:fingerprint})} onAsk={() => openAskSlate(current.relatedNotes.length ? {scope:"selected",noteIds:current.relatedNotes.slice(0,6).map((item) => item.noteId),selectedText:current.content.slice(0,4000),question:"What do I already know about this capture, where could it belong, and how does it differ from the related notes?"} : {scope:"library",selectedText:current.content.slice(0,4000),question:"What do I already know about this capture, and where could it belong?"})}/>
    </div>}
    <PreviewDialog preview={preview} busy={busy} error={error} onChange={setPreview} onClose={() => {setPreview(null);setError(null);}} onConfirm={async () => { if(!preview) return; setBusy(true); setError(null); try { if(preview.kind === "append") { const target=await api.note(preview.targetId); if(target.revision !== preview.targetRevision || target.title !== preview.targetTitle) throw new Error("The target note changed after this preview was prepared. Close the preview and review the latest note before appending."); await drafts.put({key:`${workspace.scope}:${target.id}`,id:target.id,path:target.path,baseRevision:target.revision,baseSource:target.markdown,source:preview.proposed,updatedAt:new Date().toISOString()}); local.setSuggestion(preview.item.suggestedActions.find((item) => item.action === "append" && item.targetNoteId === target.id)?.fingerprint ?? `append:${target.id}`,"accepted"); setPreview(null); workspace.open(target.id); } else { const note=preview.kind === "question" ? await api.question(preview.folder,preview.name,preview.title,preview.content) : await api.create(preview.folder,preview.name,{title:preview.title,initialMarkdown:`# ${preview.title}\n\n${preview.content.trim()}\n`}); setPreview(null); setCreated({id:note.id,item:preview.item}); void cache.invalidateQueries({queryKey:["folder"]}); } } catch(caught){setError(caught);} finally{setBusy(false);} }}/>
    <Modal open={!!created} onClose={() => setCreated(null)} title="Note created" description="The original Inbox capture is unchanged.">{created && <div className="form-stack"><p>You can open the new note now or explicitly mark the capture processed.</p><div className="dialog-actions"><Button variant="outline" onClick={() => { workspace.open(created.id); setCreated(null); }}>Open note</Button><Button onClick={() => { local.setItem(created.item.captureId,created.item.captureHash,"processed"); setCreated(null); }}>Mark capture processed</Button></div></div>}</Modal>
    <details className="knowledge-diagnostics"><summary>Inbox diagnostics</summary><pre>{JSON.stringify(query.data?.diagnostics,null,2)}</pre></details>
  </div>;
}

function TriageDetail({item,remaining,zero,state,onOpen,onAction,onKeep,onLater,onDismiss,onNotRelevant,onMove,onDelete,onRelated,onOverlap,onLinks,onGap,onAsk}:{item:InboxTriageAnalysis;remaining:number;zero:boolean;state:string;onOpen:()=>void;onAction:(action:InboxTriageSuggestion)=>void;onKeep:()=>void;onLater:()=>void;onDismiss:(action:InboxTriageSuggestion)=>void;onNotRelevant:(action:InboxTriageSuggestion)=>void;onMove:()=>void;onDelete:()=>void;onRelated:(id:string)=>void;onOverlap:()=>void;onLinks:()=>void;onGap:(fingerprint:string)=>void;onAsk:()=>void}) {
  const primary=item.suggestedActions[0]; return <div className="inbox-triage-detail scroll-area" role="region" aria-label="Selected Inbox capture"><header><div><span className="eyebrow">{typeLabel(item)} · {state}</span><h2>{item.title}</h2></div>{zero && <span>{remaining} remaining</span>}</header><p className="inbox-capture-content">{item.content}</p>
    <section><h3>Likely context</h3>{item.possibleProjects.length ? <div className="inbox-context-list">{item.possibleProjects.map((project) => <div key={project.path}><strong>{project.path}</strong><small>{project.explanation}</small></div>)}</div> : <p className="muted">No project has enough evidence yet.</p>}{item.concepts.length > 0 && <div className="inbox-concepts">{item.concepts.map((concept) => <span key={concept.id}>{concept.name}</span>)}</div>}</section>
    {(item.overlapFindings.length > 0 || item.linkTargets.length > 0) && <section className="inbox-warning"><h3><Layers3 size={15}/>Existing knowledge</h3>{item.overlapFindings.map((finding) => <p key={finding.id}><strong>{finding.label}</strong> {finding.explanation}</p>)}<div>{item.overlapFindings.length > 0 && <Button size="sm" variant="ghost" onClick={onOverlap}>Similar knowledge exists</Button>}{item.linkTargets.length > 0 && <Button size="sm" variant="ghost" onClick={onLinks}>{item.linkTargets.length} likely target note{item.linkTargets.length === 1 ? "" : "s"}</Button>}</div></section>}
    <section><h3>Related knowledge</h3>{item.relatedNotes.length ? <div className="inbox-related">{item.relatedNotes.map((note) => <button key={note.noteId} onClick={() => onRelated(note.noteId)}><span><strong>{note.title}</strong><small>{note.reasons.join(" · ")} · {note.path}</small></span><ArrowUpRight size={14}/></button>)}</div> : <p className="muted">No strong related notes were found.</p>}</section>
    {item.knowledgeGaps.length > 0 && <section><h3>May address a knowledge gap</h3>{item.knowledgeGaps.map((gap) => <button className="inbox-gap" key={gap.id} onClick={() => onGap(gap.fingerprint)}><CircleHelp size={15}/><span><strong>{gap.title}</strong><small>{gap.summary}</small></span><ChevronRight size={14}/></button>)}</section>}
    <section className="inbox-suggested"><h3>Possible action</h3>{primary && <div><strong>{primary.label}</strong><p>{primary.explanation}</p><div><Button onClick={() => onAction(primary)}>Review</Button><Button size="sm" variant="ghost" onClick={() => onDismiss(primary)}>Dismiss suggestion</Button><Button size="sm" variant="ghost" onClick={() => onNotRelevant(primary)}>Not relevant</Button></div>{item.suggestedActions.slice(1).filter((suggestion) => suggestion.action !== "keep").slice(0,3).map((suggestion) => <button className="inbox-secondary-action" key={suggestion.fingerprint} onClick={() => onAction(suggestion)}><span><strong>{suggestion.label}</strong><small>{suggestion.explanation}</small></span><ChevronRight size={14}/></button>)}</div>}</section>
    <div className="inbox-detail-actions"><Button onClick={onKeep}><Check size={15}/>Keep</Button><Button variant="outline" onClick={onMove}><FolderInput size={15}/>Organize</Button><Button variant="outline" onClick={onLater}><Clock3 size={15}/>Later</Button><Button variant="ghost" onClick={onAsk}><MessageCircleQuestion size={15}/>Ask Slate</Button><Button variant="ghost" onClick={onOpen}>Open note</Button><Button variant="ghost" onClick={onDelete}>Delete…</Button><MoreHorizontal size={15} className="muted"/></div>
  </div>;
}

function PreviewDialog({preview,busy,error,onChange,onClose,onConfirm}:{preview:Preview|null;busy:boolean;error:unknown;onChange:(value:Preview)=>void;onClose:()=>void;onConfirm:()=>Promise<void>}) {
  if(!preview) return null; const append=preview.kind === "append"; return <Modal open onClose={onClose} title={append ? "Append to existing note" : preview.kind === "question" ? "Convert to Question" : "Create note from capture"} description="Review the exact draft. The Inbox capture remains unchanged." wide>{append ? preview.loading ? <Loading label="Preparing append preview…"/> : <div className="form-stack"><p><strong>Target note</strong><br/>{preview.targetTitle}</p><p><strong>Suggested location</strong><br/>End of note under a new “Captured thought” heading</p><details><summary>Existing content context</summary><pre className="inbox-append-context">{preview.targetContext}</pre></details><label>Proposed browser draft<textarea rows={14} value={preview.proposed} onChange={(event) => onChange({...preview,proposed:event.target.value})}/></label>{preview.error != null && <ErrorMessage error={preview.error}/>}</div> : <div className="form-stack"><label>Title<input value={preview.title} onChange={(event) => onChange({...preview,title:event.target.value,name:safeName(event.target.value)})}/></label><label>File name<input value={preview.name} onChange={(event) => onChange({...preview,name:event.target.value})}/></label><label>Destination folder<input value={preview.folder} placeholder="Library root" onChange={(event) => onChange({...preview,folder:event.target.value})}/></label><FolderPicker onSelect={(folder) => onChange({...preview,folder})}/><label>Content<textarea rows={10} value={preview.content} onChange={(event) => onChange({...preview,content:event.target.value})}/></label>{preview.kind === "question" && <pre className="inbox-question-preview">type: question{"\n"}status: open{"\n"}title: {preview.title}</pre>}</div>}{error != null && <ErrorMessage error={error}/>}<div className="dialog-actions"><Button variant="outline" onClick={onClose} disabled={busy}>Cancel</Button><Button onClick={() => void onConfirm()} disabled={busy || (append ? preview.loading || !preview.proposed.trim() : !preview.title.trim() || !preview.name.trim())}>{busy ? "Working…" : append ? "Open as browser draft" : preview.kind === "question" ? "Create reviewed question" : "Create reviewed note"}</Button></div></Modal>;
}
