import { describe, expect, it } from "vitest";
import type { AssetListing, IntelligenceStatus, LinkIssue, Links, Note } from "@/lib/api/contracts";
import type { KnowledgeIssue } from "@/lib/intelligence/knowledge-issues";
import type { KnowledgeOverlap } from "@/lib/intelligence/overlap";
import type { LinkSuggestion } from "@/lib/intelligence/smart-links";
import type { KnowledgeConcept } from "@/lib/intelligence/concepts";
import { aggregateLibraryHealth, HEALTH_LIMITS, type HealthSources } from "@/lib/intelligence/health";

let sequence = 1;
function note(title: string, markdown = `# ${title}\n\nUseful prose.`, path = `Projects/${title}.md`): Note { const id = `00000000-0000-4000-8000-${String(sequence++).padStart(12, "0")}`; return { id, title, path, markdown, revision: `r-${sequence}` }; }
function links(source: Note, connected = true): Links { return { noteId: source.id, outgoing: connected ? [{ raw: "[[Target]]", target: "Target", state: "resolved", targetId: "target", targetPath: "Target.md", targetTitle: "Target", kind: "wiki" }] : [], backlinks: [] }; }
function notes(...values: Note[]): HealthSources { return { notes: values.map((value) => ({ note: value, links: links(value) })) }; }
function linkIssue(source: Note, ambiguous = false): LinkIssue { return { sourceId: source.id, sourceTitle: source.title, sourcePath: source.path, sourceRevision: source.revision, link: { raw: "[[Missing]]", target: "Missing", state: "unresolved", targetId: null, targetPath: null, targetTitle: null, kind: "wiki", start: 10, length: 11, candidates: ambiguous ? ["A.md", "B.md"] : [] } }; }
function knowledge(sourceA: Note, sourceB: Note, kind = "architecture", evidence = "strong-conflict"): KnowledgeIssue { return { issueId: "issue", fingerprint: `issue-${kind}-${evidence}`, kind, evidence, title: "Knowledge issue", explanation: "The current sources disagree.", state: "open", sourceA: { claimId: "a", noteId: sourceA.id, revision: sourceA.revision, path: sourceA.path, title: sourceA.title }, sourceB: { claimId: "b", noteId: sourceB.id, revision: sourceB.revision, path: sourceB.path, title: sourceB.title }, staleClaimId: null, projectPath: "Projects", currentCurrent: true, createdAt: "2026-10-04T10:00:00Z" } as KnowledgeIssue; }
function overlap(sourceA: Note, sourceB: Note, kind = "exact-duplicate"): KnowledgeOverlap { return { id: "overlap", fingerprint: `overlap-${kind}`, kind, state: "open", label: "Overlap", explanation: "The notes overlap.", noteA: { noteId: sourceA.id, title: sourceA.title, path: sourceA.path }, noteB: { noteId: sourceB.id, title: sourceB.title, path: sourceB.path }, sharedSections: [], uniqueSectionsA: [], uniqueSectionsB: [], sharedClaims: [], deterministicSignals: ["Same normalized content"], classification: "deterministic", projectPath: "Projects", hasKnowledgeIssue: false, createdAt: "2026-10-04T10:00:00Z", schemaVersion: 1 } as unknown as KnowledgeOverlap; }
function suggestion(sourceA: Note, sourceB: Note, type = "mention"): LinkSuggestion { return { id: "link", fingerprint: `link-${type}`, sourceNoteId: sourceA.id, sourceRevision: sourceA.revision, sourceHash: "hash", sourceTitle: sourceA.title, sourcePath: sourceA.path, target: { noteId: sourceB.id, title: sourceB.title, path: sourceB.path }, alternateTargets: [], sourceExcerpt: "Direct mention", suggestionType: type, suggestedLinkKind: "wiki", signals: ["Direct mention"], explanation: "The source names the target.", status: "open", ambiguous: false, hasKnowledgeIssue: false, projectPath: "Projects", createdAt: "2026-10-04T10:00:00Z", schemaVersion: 1 } as unknown as LinkSuggestion; }
function concept(source: Note): KnowledgeConcept { return { id: "concept-slate", canonicalName: "Slate", normalizedName: "slate", aliases: ["Slate Lib", "Slate.Library"], kind: "Project", sourceCount: 1, currentSourceCount: 1, firstSeen: null, lastSeen: null, projectPaths: ["Projects"], tags: [], importanceSignals: [], openQuestionCount: 0, knowledgeIssueCount: 0, contentHash: "concept-hash", schemaVersion: 1, members: [{ noteId: source.id, title: source.title, path: source.path }], relationships: [] } as unknown as KnowledgeConcept; }
function asset(id: string, referenceCount: number, valid = true): AssetListing { return { metadata: { id, originalFilename: valid ? "diagram.png" : "", contentType: valid ? "image/png" : "", byteSize: 100, extension: valid ? ".png" : "", inlineImage: true, createdAt: "2026-10-04T10:00:00Z", sha256: valid ? "abc" : "" }, referenceCount }; }

describe("Library Health aggregation", () => {
  it("turns unresolved canonical links into needs-attention findings", () => { const source = note("A"); const result = aggregateLibraryHealth({ linkIssues: [linkIssue(source)] }); expect(result.items[0]).toMatchObject({ kind: "broken-link", category: "links", priority: "needs-attention", targetWorkspace: "link-health" }); });
  it("distinguishes ambiguous canonical links", () => { const source = note("A"); expect(aggregateLibraryHealth({ linkIssues: [linkIssue(source, true)] }).items[0].kind).toBe("ambiguous-link"); });
  it("reuses contradiction findings and specialist routing", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ knowledgeIssues: [knowledge(a, b)] }).items[0]).toMatchObject({ category: "consistency", healthOnly: false, targetWorkspace: "knowledge-issues" }); });
  it("prioritizes current strong conflicts", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ knowledgeIssues: [knowledge(a, b)] }).items[0].priority).toBe("needs-attention"); });
  it("labels answered questions for review", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ knowledgeIssues: [knowledge(a, b, "answered-question", "possible-stale")] }).items[0]).toMatchObject({ kind: "answered-question", priority: "worth-reviewing" }); });
  it("labels likely superseded knowledge as stale and worth reviewing", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ knowledgeIssues: [knowledge(a, b, "supersession", "likely-superseded")] }).items[0]).toMatchObject({ kind: "stale-knowledge", priority: "worth-reviewing", evidenceLevel: "strongly-indicated" }); });
  it("reuses exact duplicate findings", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ overlaps: [overlap(a, b)] }).items[0]).toMatchObject({ category: "overlap", priority: "needs-attention", healthOnly: false }); });
  it("keeps partial overlap informational", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ overlaps: [overlap(a, b, "partial-overlap")] }).items[0].priority).toBe("informational"); });
  it("routes a possibly absorbed note through overlap review", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ overlaps: [overlap(a, b, "possibly-absorbed")] }).items[0]).toMatchObject({ kind: "possibly-absorbed", priority: "worth-reviewing", targetWorkspace: "knowledge-overlap" }); });
  it("routes missing relationships to Smart Linking", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ linkSuggestions: [suggestion(a, b)] }).items[0]).toMatchObject({ category: "relationships", targetWorkspace: "link-opportunities" }); });
  it("treats better targets as link maintenance", () => { const a = note("A"), b = note("B"); expect(aggregateLibraryHealth({ linkSuggestions: [suggestion(a, b, "better_target")] }).items[0].category).toBe("links"); });
  it("finds canonical orphan notes", () => { const source = note("Solo"); const result = aggregateLibraryHealth({ notes: [{ note: source, links: links(source, false) }] }); expect(result.items.some((item) => item.kind === "orphan-note")).toBe(true); });
  it.each(["Daily/2026-10-04.md", "inbox/Capture.md", "Templates/Meeting.md", "README.md", "index.md"])("excludes intentional standalone location %s from orphan findings", (path) => { const source = note("Standalone", "# Standalone\n\nContent.", path); const result = aggregateLibraryHealth({ notes: [{ note: source, links: links(source, false) }] }); expect(result.items.some((item) => item.kind === "orphan-note")).toBe(false); });
  it("finds heading-only notes without classifying normal notes", () => { const empty = note("Empty", "---\nid: one\n---\n# Empty\n## Heading"); const full = note("Full", "# Full\n\nActual prose."); const result = aggregateLibraryHealth(notes(empty, full)); expect(result.items.filter((item) => item.kind === "empty-note").map((item) => item.noteIds[0])).toEqual([empty.id]); });
  it("finds missing referenced assets", () => { const source = note("Asset", "# Asset\n\n![x](asset://aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa)"); const result = aggregateLibraryHealth({ ...notes(source), assets: [] }); expect(result.items.some((item) => item.kind === "missing-asset")).toBe(true); });
  it("finds unreferenced assets", () => { expect(aggregateLibraryHealth({ assets: [asset("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", 0)] }).items[0].kind).toBe("unreferenced-asset"); });
  it("does not flag a valid referenced asset", () => { expect(aggregateLibraryHealth({ assets: [asset("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", 2)] }).items).toHaveLength(0); });
  it("finds invalid asset metadata", () => { expect(aggregateLibraryHealth({ assets: [asset("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", 1, false)] }).items[0]).toMatchObject({ kind: "invalid-asset-metadata", priority: "needs-attention" }); });
  it("finds unterminated frontmatter", () => { const source = note("Bad", "---\nid: bad\n# Bad"); expect(aggregateLibraryHealth(notes(source)).items.some((item) => item.kind === "invalid-frontmatter")).toBe(true); });
  it("finds duplicate frontmatter IDs", () => { const a = note("A", "---\nid: shared\n---\n# A\n\nOne."), b = note("B", "---\nid: shared\n---\n# B\n\nTwo."); expect(aggregateLibraryHealth(notes(a, b)).items.some((item) => item.kind === "duplicate-note-id")).toBe(true); });
  it("finds concept identity ambiguity", () => { const source = note("Slate"); expect(aggregateLibraryHealth({ concepts: [concept(source)] }).items[0]).toMatchObject({ category: "concepts", targetWorkspace: "concepts" }); });
  it("associates reused findings with derived concepts", () => { const a = note("A"), b = note("B"); const result = aggregateLibraryHealth({ knowledgeIssues: [knowledge(a, b)], concepts: [concept(a)] }); expect(result.items.find((item) => item.kind === "contradiction")?.conceptIds).toContain("concept-slate"); });
  it("reports persistent intelligence failures", () => { const status = { failedJobs: 2, failedChunksThisRun: 1, lastIndexedAt: null, lastError: "Embedding failed" } as IntelligenceStatus; expect(aggregateLibraryHealth({ intelligence: status }).items[0]).toMatchObject({ category: "intelligence", priority: "needs-attention", targetWorkspace: "diagnostics" }); });
  it("honors health-only local review state", () => { const source = note("Solo"); const first = aggregateLibraryHealth({ notes: [{ note: source, links: links(source, false) }] }); const orphan = first.items.find((item) => item.kind === "orphan-note")!; const next = aggregateLibraryHealth({ notes: [{ note: source, links: links(source, false) }] }, { status: "dismissed" }, { health: { [orphan.fingerprint]: { state: "dismissed" } } }); expect(next.items).toHaveLength(1); });
  it("reuses underlying review state", () => { const a = note("A"), b = note("B"), issue = knowledge(a, b); const result = aggregateLibraryHealth({ knowledgeIssues: [issue] }, { status: "resolved" }, { knowledge: { [issue.fingerprint]: { fingerprint: issue.fingerprint, state: "resolved", reviewedAt: "2026-10-04T10:00:00Z" } } }); expect(result.items[0].reviewState).toBe("resolved"); });
  it("filters by category, priority, project, note, concept, and search", () => { const a = note("Architecture"), b = note("Reading", undefined, "Research/Reading.md"); const sources = { linkIssues: [linkIssue(a)], linkSuggestions: [suggestion(a, b)], concepts: [concept(a)] }; expect(aggregateLibraryHealth(sources, { category: "links" }).items.every((item) => item.category === "links")).toBe(true); expect(aggregateLibraryHealth(sources, { priority: "worth-reviewing" }).items.every((item) => item.priority === "worth-reviewing")).toBe(true); expect(aggregateLibraryHealth(sources, { project: "Projects" }).items.length).toBeGreaterThan(0); expect(aggregateLibraryHealth(sources, { noteId: a.id }).items.length).toBeGreaterThan(0); expect(aggregateLibraryHealth(sources, { concept: "concept-slate" }).items.length).toBeGreaterThan(0); expect(aggregateLibraryHealth(sources, { search: "architecture" }).items.length).toBeGreaterThan(0); });
  it("paginates deterministically", () => { const values = Array.from({ length: 7 }, (_, index) => linkIssue(note(`Note ${index}`))); const one = aggregateLibraryHealth({ linkIssues: values }, { page: 0, limit: 3 }), two = aggregateLibraryHealth({ linkIssues: values }, { page: 1, limit: 3 }); expect(one.items).toHaveLength(3); expect(two.items).toHaveLength(3); expect(one.items[0].id).not.toBe(two.items[0].id); expect(one.total).toBe(7); });
  it("uses deterministic stable ordering", () => { const a = note("Zulu"), b = note("Alpha"); const before = aggregateLibraryHealth({ linkIssues: [linkIssue(a), linkIssue(b)] }).items.map((item) => item.fingerprint); const after = aggregateLibraryHealth({ linkIssues: [linkIssue(b), linkIssue(a)] }).items.map((item) => item.fingerprint); expect(after).toEqual(before); });
  it("does not reopen a health-only finding after an unrelated edit", () => { const source = note("Solo"); const first = aggregateLibraryHealth({ notes: [{ note: source, links: links(source, false) }] }); const orphan = first.items.find((item) => item.kind === "orphan-note")!; const changed = { ...source, revision: "r-unrelated", markdown: `${source.markdown}\n\nUnrelated prose edit.` }; const next = aggregateLibraryHealth({ notes: [{ note: changed, links: links(changed, false) }] }, { status: "dismissed" }, { health: { [orphan.fingerprint]: { state: "dismissed" } } }); expect(next.items.find((item) => item.kind === "orphan-note")?.fingerprint).toBe(orphan.fingerprint); });
  it("reopens a health-only finding when its evidence identity changes", () => { const firstId = "11111111-1111-4111-8111-111111111111", secondId = "22222222-2222-4222-8222-222222222222"; const source = note("Assets", `# Assets\n\nasset://${firstId}`); const first = aggregateLibraryHealth({ notes: [{ note: source, links: links(source, true) }], assets: [] }); const missing = first.items.find((item) => item.kind === "missing-asset")!; const changed = { ...source, revision: "r-material", markdown: `# Assets\n\nasset://${secondId}` }; const next = aggregateLibraryHealth({ notes: [{ note: changed, links: links(changed, true) }], assets: [] }, { status: "open" }, { health: { [missing.fingerprint]: { state: "dismissed" } } }); expect(next.items.find((item) => item.kind === "missing-asset")?.fingerprint).not.toBe(missing.fingerprint); });
  it("does not infer missing assets from a bounded partial inventory", () => { const source = note("Assets", "# Assets\n\nasset://11111111-1111-4111-8111-111111111111"); const result = aggregateLibraryHealth({ notes: [{ note: source, links: links(source, true) }], assets: [], assetInventoryComplete: false }); expect(result.items.some((item) => item.kind === "missing-asset")).toBe(false); });
  it("caps page size and source processing", () => { const values = Array.from({ length: HEALTH_LIMITS.maxLinkIssues + 10 }, (_, index) => linkIssue(note(`Note ${index}`))); const result = aggregateLibraryHealth({ linkIssues: values }, { limit: 999 }); expect(result.pageSize).toBe(HEALTH_LIMITS.maxPageSize); expect(result.total).toBe(HEALTH_LIMITS.maxLinkIssues); });
  it("returns partial results with explicit source failures", () => { const source = note("A"); const result = aggregateLibraryHealth({ linkIssues: [linkIssue(source)], failedSources: ["assets"] }); expect(result.items).toHaveLength(1); expect(result.degraded).toMatch(/assets/); expect(result.diagnostics.failedSourceQueries).toEqual(["assets"]); });
  it("does not mutate concept aliases while fingerprinting", () => { const source = note("Slate"), value = concept(source); const aliases = [...value.aliases]; aggregateLibraryHealth({ concepts: [value] }); expect(value.aliases).toEqual(aliases); });
});
